### ISSUE TITLE
Signal end of life of an ExposedThing to the related ConsumedThings

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#114]
An ExposedThing may be destroyed by its local runtime by a script invoking `thing.destroy()` (in the new API, as in #113). In that case the ConsumedThing objects that were created by consuming the TD of `thing` should be notified. This is not a TD change per se. We have a few options how to handle this:

1. Don't support it (and neither support `thing.destroy()`), because not all protocols might support signaling for end of life events like this (to be verified).
2. Support it with a special event (reserved/standardized event name) that is specified in the TD spec and the Scripting spec. 
3. Support it with the current TD change notification mechanism, except that instead of an object, `null` is passed when the TD/ExposedThing was removed (from its runtime and/or from directories).

The algorithm for `thing.destroy()` would work like this:
- send notification that a Thing with given `id` was destroyed
- delivery mechanism is not specified, could be encapsulated by protocol bindings or runtime implementations (but it is a discussion similar to lifecycle and discovery discussions).
- each runtime that listens to this notification, will check if it has active ConsumedThing objects with `id` equal to the one signaled. If yes, it invokes the observer of the corresponding ConsumedThing object with `null` instead of an object parameter of type `ThingDescription`.

I will create tracking issues in Security and TD repositories.

**Comment by mkovatsc** [comment]
I would connect it to the best-effort TD change notifications.

When this is mapped to CoAP Observe, there is a pretty neat mechanism:

TD change notifications are sent as 2.05 Observe notifications. When the Thing is destroyed, and hence the TD disappears, a final 4.04 Not Found notification would be sent (informing that the resource is gone) with the same token (same observation), but without Observe option (also informing that no further notifications will be sent).

This can also work for HTTP long-poll, but other protocols may lack the metadata for such a mechanism.

**Comment by mmccool** [comment]
Some comments on security here: https://github.com/w3c/wot-security/issues/93
Wondering how TD change notifications are protected/authenticated/authorized.

**Comment by zolkis** [comment]
As discussed in https://www.w3.org/2018/09/17-wot-minutes.html, we should: 
- include algorithm for best-effort notification of Thing (TD change) observers with passing `null` as argument instead of a Thing Description. 
- Also, update the relevant text of ConsumedThing (what happens when a ConsumedThing is observed).
