### ISSUE TITLE
Extract normative assertions for testing

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-scripting-api#117]
For defining test cases we need to extract and name all the normative assertions.

I have [automated this process](https://github.com/w3c/wot-thing-description/pull/138) but it requires following some conventions in the markup of normative assertions.  I'll test the automation first in the TD spec and when it's reasonably stable can make a similar PR for the scripting API spec.

**Comment by zolkis** [comment]
I would argue that it's enough to use MAY, MUST, SHOULD, as ReSpec will handle them as normative assertions and every occurrence is as well defined as it would be by a special tag. There is no separate normative and non-normative use of MAY, MUST, SHOULD, etc. So let's keep the specs clean.

**Comment by danielpeintner** [comment]
Close in favor of https://github.com/w3c/wot-scripting-api/issues/190
