### ISSUE TITLE
issue with addProperty/addAction/addEvent for ExposedThing

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#120]
The [ExposedThing](https://rawgit.com/zolkis/wot-scripting-api/master/index.html#the-exposedthing-interface) interface allows adding interaction.

For example an ThingProperty needs to be passed for adding a property.  ThingProperty has `get()` and `set()` methods. I don't htink these are required nor desired when simply initializing a property. The get() and set() are needed later, once the ExposedThing  got registered with actual handlers.. 

I think addProperty() should be initialized with PropertyInit (maybe also with getter)

**Comment by zolkis** [comment]
Right, these should all be ..Init structures.
