### ISSUE TITLE
ThingAction misses input parameter for run()

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#121]
I think actions might need input to be abele to run and we used to have them before also
see https://www.w3.org/TR/wot-scripting-api/#the-exposedthing-interface

Hence, I suggest changing 

`Promise<any> run();`

to 

`Promise<any> run(any parameter?);`

**Comment by zolkis** [comment]
Fixed in #119

**Comment by danielpeintner** [comment]
Maybe one minor addition. I think the input could be marked as _optional_ in the WebIDL.

Similarly, I believe that _most_ of the "init" parameters should be marked as optional.
see ThingInit, PropertyInit et cetera.

According to the update for `ThingAction` it seems the input is required and output is not. I believe both can be optional, don't you think?

**Comment by zolkis** [comment]
In the dictionaries the `value` (init) properties are optional.
I have made the arg to `run()` optional, and added text to clarify `ThingAction.input` and `output`.

**Comment by danielpeintner** [comment]
According to my understanding we agree that properties in `XXXInit` interfaces should be all optional.

However, I see that `InteractionInit`, `PropertyInit`, `ActionInit` et cetera are all required in WebIDL expect some exceptions (e.g., `output` in `ActionInit` is optional while others are not?)

Note: I believe I am checking the latest updates from https://github.com/w3c/wot-scripting-api/pull/119 (see https://rawgit.com/zolkis/wot-scripting-api/master/index.html#the-actioninit-dictionary)

**Comment by zolkis** [comment]
The `...Init` constructs are not interfaces, but dictionaries, where by default all properties are optional, unless marked `required`.

**Comment by danielpeintner** [comment]
> The ...Init constructs are not interfaces, but dictionaries, where by default all properties are optional, unless marked required.

Then I just don't understand why output has "?" and the others not?

```
dictionary ActionInit : InteractionInit {
    DataSchema  input;
    DataSchema? output;
    DOMString   description;
};
```

**Comment by zolkis** [comment]
Also `input` should be nullable (marked by `?`). I made the correction.

**Comment by danielpeintner** [comment]
Thanks!

I am still a bit confused about the difference of "nullable" vs "optional" in The `...Init` dictionaries ...

**Comment by zolkis** [comment]
The `nullable` is expressed with `?`. It is used in the algorithms.
In dictionaries, all properties are optional (i.e. if not provided, the value is `undefined`), except if they are marked as `required` in WebIDL, or marked as required in the text description.

**Comment by danielpeintner** [comment]
`run` is now `invoke` (see https://github.com/w3c/wot-scripting-api/commit/fe9f0664e67129d204277829338fd31ad7283888)

Besides that my other comments are resolved.
