### ISSUE TITLE
Clarification (avoiding confusion with term "name")

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#122]
I suggest changing the term "name" to "key" in the places where it is used as a _key_ in an object/map 
e.g.,  `ExposedThing  addProperty(DOMString name, ThingProperty property);`

**Comment by zolkis** [comment]
IMHO `name` is just fine. There is no misunderstanding about that it represents a property name.

**Comment by danielpeintner** [comment]
That's a matter of opinion and I am fine with sticking to `name` also.
