### ISSUE TITLE
Avoiding same name for functions in interfaces

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#124]
With the simplified TD it seems to be a legitimate way to implement scripting by extending JSON objects and attaching handlers. For example one could parse a JSON thing description and add handlers to it

```
"properties": {
        "status" : {
            "type": "string"
        }
}

```
However, dynamically adding functions work only (as far as I know) if there are no colliding functions.
Unfortunately, The ThingProperty interface  has such colliding functions for `get`.

```
interface ThingProperty : Interaction {
    // getter for PropertyInit properties
    getter any   (DOMString name);
    // get and set interface for the Property
    Promise<any> get();
    Promise      set(any value);
};
```

There is on `get` for retrieving the property value and there is another `get` for getting properties.

Hence, I suggest renaming getting and setting the property value again to `read` and `write`. 

If I miss anything here please let me know!

**Comment by zolkis** [comment]
There is only one `get()`... the others are getters.
Anyway you can raise renaming (back) to `read` and `write`, but since these are asynchronous, maybe `fetch` and `update` would be more accurate terms, even if more overloaded than the rest.

**Comment by zolkis** [comment]
#127 is active. Should we discuss the same things both in this issue and there?

**Comment by danielpeintner** [comment]
Mhhh, when I looked previously https://github.com/w3c/wot-scripting-api/issues/127 was closed ...
