### ISSUE TITLE
Should Thing Directory Interface (register/unregister/discover) be part of WoT standard?

### ISSUE THREAD

**Issue by farshadahmadi** [w3c/wot-scripting-api#126]
Thing Directory APIs including register/unregister/discover are part of WoT standard right now. But Thing Directory can also be described by a Thing Description through narrow waist interaction models. Then the client can get the TD, parse it, and communicate with it.

**Comment by mkovatsc** [comment]
Scripts also need a way to discover without a directory, e.g., to trigger a multicast discovery conducted by the WoT Runtime. Hence, `discover()` needs to stay.

`register()` and `unregister()` are mainly convenience functions. Here we could discuss to keep the Scripting API slim and remove them, and rely on directories having TDs with standard annotations for registration, registration update, de-registration, and lookups.

**Comment by zolkis** [comment]
To be discussed in Lyon F2F.

**Comment by zolkis** [comment]
With #174 we removed register() and unregister(), but kept discover(). Closing for now, reopen if needed.
