### ISSUE TITLE
Why is expose() asynchronous?

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#130]
The spec says `Promise<void> expose();`.
Implementing node-wot, I could not find a reason, why it would need to be asynchronous.

Any other experiences?

**Comment by zolkis** [comment]
Right, then the idea about what `expose()` is supposed to do was different than now. We need to specify the algorithm for it. It would be helpful to link the implementation, or shortly summarize the functionality.

**Comment by draggett** [comment]
In my implementation expose() is asynchronous as it can take some time to set up and initialise when the exposed thing depends upon other things.

**Comment by zolkis** [comment]
The signature could eventually stay asynchronous, and the node-wot implementation can resolve it immediately.

**Comment by zolkis** [comment]
Fixed in #128 as synchronous API.
