### ISSUE TITLE
Why is emitEvent() asynchronous?

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#131]
The spec says `Promise<void> emitEvent(DOMString eventName, any payload);`.
Is the idea that the promise resolves, when all subscribers have been notified? Is this feasible?

**Comment by mkovatsc** [comment]
Not sure if this will be changed to `emit()` on ExposedThingEvent objects; questions holds there as well.

**Comment by zolkis** [comment]
Yes, this doesn't need to be asynchronous. I think the idea was the promise resolves when all the notifications were sent out (not when all subscribers have been notified). We need to discuss about event handling anyway, e.g. on next week's Scripting call.

**Comment by zolkis** [comment]
Fixed in #128
