### ISSUE TITLE
Align Security Vocabulary Definition with TDs

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#140]
The current Scripting API document is *behind* aligning the latest security vocabulary definitions.

Maybe we can find a way in the future to automatically propagate changes to security to scripting also (to avoid such mis-alignments).

Some differences I found in https://w3c.github.io/wot-scripting-api/ compared to [TD](https://w3c.github.io/wot-thing-description/#sec-security-vocabulary-definition).

* 8.1 The SecuritySchemeType enumeration type
  * misses "nosec", "cert", "psk", "public"
* 8.4 The BasicSecurityScheme dictionary
  * change "pname" to "name"
  * change type of "in" to AuthenticationType in WebIDL
* 8.6 The BearerSecurityScheme dictionary
* 8.7 The PopSecurityScheme dictionary
* 8.8 The ApikeySecurityScheme dictionar
* 8.9 The OAuth2SecurityScheme dictionary
  * Attributes changed a lot

Shall I try to work on a PR to align?

**Comment by zolkis** [comment]
As discussed on the Scripting call, I will remove definitions of all these dictionaries and will refer to TD spec.

**Comment by danielpeintner** [comment]
https://github.com/w3c/wot-scripting-api/pull/138
