### ISSUE TITLE
General Scripting API review comments (2018-09-04)

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#141]
Below some minor comments for further discussions ...

# # 5. The ExposedThing interface

Comment in WebIDL
change from
`// define how to expose and run the Thing`
to
`// methods to expose and destroy the Thing`

# # 6.8 The ThingProperty interface

typo "o9ne"

## 6.16 The value-matching algorithm

* Step 1 seems wrong to me.
If type is undefined (or not set) it is true by default.

* Step 7 can be simplified by first checking for array

* Step 8
Why does type "object" accept null? I don't think this is the case in JSON schema

**Comment by zolkis** [comment]
> Step 1 seems wrong to me.
If type is undefined (or not set) it is true by default.

If type is not defined in the model, then there is no base for declaring a match IMHO. One must always declare the type in the model (unless we default to a given type, which we currently don't).

**Comment by danielpeintner** [comment]
https://github.com/w3c/wot-scripting-api/pull/138
