### ISSUE TITLE
Align argument names with terminology in TD spec

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#146]
The TD talks about identifiers for Interactions and the key in the `properties`, `actions`, and `events` objects maps to the `@id`, the identifier of the Interaction.

@mmccool I think you chose the same terminology for the security document, right?

This the Scripting API should adopt the same terminology. Note that this is related to https://github.com/w3c/wot-thing-description/issues/156, as we need to nail down the terminology (name vs title vs label vs caption vs ...)

**Comment by zolkis** [comment]
The current version of Scripting API does not re-define the terms, instead it links those definitions from the TD spec. Could you identify where the Scripting spec needs to be changed?

**Comment by mkovatsc** [comment]
It is already an issue within the TD spec. We discussed to align toward "identifier", which would need alignment here. With https://github.com/w3c/wot-thing-description/issues/194 we might align toward "name", which would be fine.

TD 5.2.2: "Each instance of a Property, Action, and Event class MUST have an **identifier** that is unique within the context of a Thing Description document"

TD 6.1.2: "Properties (and sub-properties) offered by a Thing MUST be collected in the JSON-object based properties field with (unique) Property **names** as JSON **keys**"

**Comment by zolkis** [comment]
So we should track the TD issue and do eventual changes to Scripting later.

IMHO 'name' is better than 'identifier'.

**Comment by zolkis** [comment]
AFAICT this can be closed.
