### ISSUE TITLE
Security Testing and Validation URLs return 404

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#151]
D.1 [WOT-SECURITY-TESTING]: Web of Things Security Testing and Validation. W3C. WIP. URL: https://github.com/w3c/wot-security/blob/master/wot-security-testing.md

This URL is not valid and returns 404

**Comment by zolkis** [comment]
The document doesn't exist yet (broken dependency on the security repo) and the link is marked as WIP. Discussed in Lyon that it will be added.

**Comment by zolkis** [comment]
Fixed in #174
