### ISSUE TITLE
Align with TD (name/value pairs)

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#157]
see https://github.com/w3c/wot-thing-description/issues/194

**Comment by zolkis** [comment]
Since `key` has a consistent usage in [ECMAScript](http://www.ecma-international.org/ecma-262/10.0/index.html), in the Scripting API (JavaScript) we should use that context.

**Comment by zolkis** [comment]
Any agreement on this? "key" is being used in prose only and in line with ECMAScript (one can also think about it like we are mapping "names" to "keys" in the Scripting API).

**Comment by danielpeintner** [comment]
key-value pair (as used in scripting document) is fine by me.

Having said that, TD spec uses "title" instead of "key" or "name" in some areas but this seems not to be a good match for scripting. I am OK with closing this issue.
