### ISSUE TITLE
typescript definitions: Items should not be required in an ArraySchema

### ISSUE THREAD

**Issue by hasbel** [w3c/wot-scripting-api#163]
According to the TD spec, "Items" is not a mandatory property of an ArraySchema, but in the current typescript definitions, it is defined as mandatory.

in `index.d.ts` :
```typescript
export interface ArraySchema extends BaseSchema {
    type: "array";
    items: DataSchema;
    minItems?: number;
    maxItems?: number;
}
```

should be:

```typescript
export interface ArraySchema extends BaseSchema {
    type: "array";
    items?: DataSchema;
    minItems?: number;
    maxItems?: number;
}
```

**Comment by danielpeintner** [comment]
@hasbel I think you are right. Thanks!

We are currently updating the API to a more browserfriendly API (see working branch https://github.com/danielpeintner/wot-scripting-api/blob/next-api-2019/typescript/index.d.ts)

I would like to keep this issue open and not to merge to avoid merge conflicts. Moreover keeping it open will be a reminder once we merge the outstanding updaptes. Hope this is OK for you...
