### ISSUE TITLE
Remove Discovery from Core WoT interface?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#168]
The `WoT` object offers an entry point for `discover()` (besides `consume()` and `produce()`).

While `consume` and `produce` seems to be an essential part of WoT, `discovery` could be *something* on its own, similar to a ThingBuilder which has been discussed.

Does it make sense to see discovery as such an *external* (or on-top part) of the WoT or should it be part of the core?

**Comment by zolkis** [comment]
Depends on how strong the use case for discovery is.

There is the argument that if WoT wants to be able to represent other IoT realms which do have discovery, how are we going to represent that: via a special application (i.e. not standardized API, just de-facto Thing Descriptions that expose an action like `discover`)?

The API in this spec has the advantage to propose a fairly generic common API for discover-like use cases that encapsulates protocol bindings details. It could be made optional. In that case we should apply the [TAG Client API design principle for feature detection](https://w3ctag.github.io/design-principles/#feature-detect). 

One way to detect the feature is to throw `NotSupportedError` when it's not supported. We could include that in the algorithm. However, in that case the `discover()` method still must be present on every WOT object.

**Comment by zolkis** [comment]
Will be fixed with #173.

**Comment by zolkis** [comment]
Fixed by #174.
