### ISSUE TITLE
Subscribe vs Observe Property

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#169]
The [thing description op](https://w3c.github.io/wot-thing-description/#form) field uses the terms 
* "observeproperty" and "unobserveproperty" for properties and
* "subscribeevent" and "unsubscribeevent" for events.

The Scripting API uses `subscribeProperty()` and `unsubscribeProperty()` in ConsumedThing interface.
Maybe we want to align with that regard changing it to `observeProperty()` and `unobserveProperty()` ?

For events  `subscribeEvent()` and `unsubscribeEvent()` is fine.

**Comment by zolkis** [comment]
Makes sense.
