### ISSUE TITLE
Separate the client and server interfaces

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#173]
As discussed on the Munich F2F, it would make sense to split the Scripting API into:
1. client API (ConsumedThing)
2. server API (ExposedThing and eventually ThingBuilder)
3. discovery API (ThingDiscovery), which is a special client API.

**Comment by danielpeintner** [comment]
+1

the `WoT` object is already now technically speaking just a *entry* point for consuming, producing and discovering a thing.
