### ISSUE TITLE
Adding readonly properties through ExposedThing interface

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#18]
_From @retamar on March 3, 2017 8:1_

There are any way to add a readonly property using the scripting API through ExposedThing interface?  I see that in TD we have the "writable" property but, there are no way to set it's value through ExposedThing. It seems that is not possible to assign any other property (or any interaction) metadata using the scripting AP such as stability or semantic data such as "units".

_Copied from original issue: w3c/wot#310_

**Comment by zolkis** [comment]
_From @h0ru5 on April 3, 2017 11:37_

decision to move over to new  repo

**Comment by zolkis** [comment]
Moved the issue over from the WoT IG repo.

**Comment by h0ru5** [comment]
The most basic idea would be to add a boolean field ``writeable`` to the ``ThingProperty`` dictionary
I'd suggest defaulting to ``true``

**Comment by zolkis** [comment]
Fixed in #20.
