### ISSUE TITLE
Spec: Examples using JSON string instead of object

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#181]
In Example 1, 2 and 9 a similar construct is used. 

```
let res = await fetch('https://...');
let td = await res.json();
let thing = new ConsumedThing(td);
```

The variable `td` is of type string and passed to `ConsumedThing` constructor which expects input typed as object.

Q: is there any tooling we could use to do some basic checking of examples?

**Comment by zolkis** [comment]
The `td` variable there is of type object, or array, or string, or number. In WoT case it should always resolve with an Object, as specified by the TD spec. Implementations should check for that. 
Should we include normative text about this in the Scripting spec?

**Comment by danielpeintner** [comment]
My *naive* reading was that it returns JSON text....

No further text needed. It is a sample anyway.
