### ISSUE TITLE
readProperty() does not allow for uriVariables or other parameters

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#182]
We decided in https://github.com/w3c/wot-scripting-api/issues/149 and https://github.com/w3c/wot-scripting-api/issues/166 that we do not need a specific way to convey parameters (e.g., uriVariables) to actions and properties.

I think this is correct for actions and setting properties.
`e.g., http://example.com/counter/actions/increment?step=12`
can be transformed to 
`thing.invokeAction("increment", {step: 12})`
Similarly for setting properties: e.g.,  `thing.writeProperty("temperature", {"value": 12, unit: "celsius"})` or so.

However, how can I map a temperature service that allows for defining temperature unit 
e.g., `http://example.com/service/properties/temperature?unit=celsius`
`thing.readProperty("temperature"); // How to convey the unit?`

Hence I propose to extend 
`readProperty(propertyName: string): Promise<any>;`
to
`readProperty(propertyName: string, parameter?: any): Promise<any>;`

**Comment by zolkis** [comment]
This is not a big change to do in the spec.
However, I challenge a bit the idea:
- the caller assumes the server will respect temperature readings in given units; how can we be sure of that? If the TD does not support that, what should happen? Error that the property cannot be read? (misleading). Or an error that the property cannot be read with the given options (better)? Or reply with ignoring the options (worst)?
- what if the server device exposes temperature in its "native" units, and the TD describes what are the units? then the caller can convert if needed.

Maybe we shouldn't be stuck at the given example and let's assume we might have options to any request. But then those would be protocol-native options, transparent to the WoT layer, just forwarded as they are. This would be bad for security and encapsulation reasons (raising the question was the TD designed well)?

Who would describe/standardize what the options can be? The spec? The TD?

I would say let's have a fresh look at this: in all these cases we might want to expose those interactions as Actions, not as Property read or write operations. It is an Action that can have parameters and can be used for representing composite interactions, where validation might also play a role.

This would allow to keep the interaction model and the spec simple. In the Protocol Bindings, an action to read temperature with a parameter "unit" might translate as a request using uriVariables. However, I would not expose that directly on the ConsumedThing API level.

**Comment by danielpeintner** [comment]
As mentioned let's not get stucked with *one* example.

I think it is not uncommon to pass options even to read methods.

**Comment by zolkis** [comment]
The TD spec doesn't currently support options to `observeproperty` op of PropertyAffordance. At `Form` level there is the `ExpectedResponse` which may be used for telling preferences about the response, but that currently contains only `contentType`.

The use case of reading temperature in units given by client can currently be modeled as an Action in WoT (using application-specific vocabulary for the parameter) and I think it makes sense, even though if the implementation (bindings) end up using e.g. CoAP options for this.

We can discuss about other examples as well, but in general, IMHO anything that requires some interaction with the server for retrieving information seems to work best with an Action.

Property reads are as simple as possible, happening in the units defined in the TD of the serving Thing. The client should be responsible for converting units.

We could discuss this in the main call and/or TD call.

**Comment by danielpeintner** [comment]
> The TD spec doesn't currently support options to observeproperty op of PropertyAffordance. At Form level there is the ExpectedResponse which may be used for telling preferences about the response, but that currently contains only contentType.

Not sure why `observeproperty`  should not be possible at the moment in TD.

> The use case of reading temperature in units given by client can currently be modeled as an Action in WoT (using application-specific vocabulary for the parameter) and I think it makes sense, even though if the implementation (bindings) end up using e.g. CoAP options for this.

We need to get away from the fact that it's better to do this or that. There are systems out already and we need to be able to describe them. e.g., finding products with certain facets
e.g., GET `/products/?name={name}&deliveryDate={deliveryDate}&color={color}`

**Comment by zolkis** [comment]
> We need to get away from the fact that it's better to do this or that. There are systems out already and we need to be able to describe them

That's right, but it's flexible how to define a TD for them. When it can be done with an Action, why are we forcing the concept of options to Property observe interactions. Not sure what would be the best narrow waist design there.

**Comment by zolkis** [comment]
In the Scripting call on 19.8.2019 was pointed out that in the TD spec, all InteractionAffordance (Property, Action and Event) might use `uriVariables`. Whereas implementations can encapsulate these in the case of Actions, that is not possible in the case of Property and Event definitions, therefore they should be exposed somehow to client scripts, so protocol binding details might creep up into application space. 

This is nasty design IMHO, leaving a hole for protocol-specific stuff, violating the protocol-agnostic assumption and questioning the generalization capabilities of a TD. But if the TD is like that, Scripting cannot improve on that.

**Comment by zolkis** [comment]
If we expose the uriVariables, then all interactions will have options, therefore all signatures will look nearly the same. Then further problems arise, if we are consistent along the same thought train:
- read Property, write Property will have options (that scripts need to be aware of)
- subscribing to notifications (Events and Property updates) will have options, too, that scripts need to know about
- subscriptions can be cancelled, but then why actions cannot? and why a read or write Property request cannot be cancelled? (with best effort policy, as it is usually the case with cancelling)
- why cannot we handle Property observe with an Action signature (providing the listener as a parameter to the method call, using `null` for cancelling)?
- Moreover, why can't we handle all subscriptions with one call?
`thing.subscribe(name, options, listener)` where `name` could be an Event or a Property?
There should be one namespace for all interactions in the TD spec, really, but even if they are separate, the interaction type could be one of the options...

A ConsumedThing interface could also look like this (following the TD spec more closely, extreme case, getting again close to a generic request type interface, which actually it is, regardless how much cosmetics we put on it):
```javascript
interface ConsumedThing {
  Promise<any> request(TdOperation op, DOMString name, optional InteractionOptions opts);
  ThingDescription td();
};

enum { 
  "readproperty", "readmultipleproperties", "readallproperties", 
  "writeproperty", "writemultipleproperties", "writeallproperties", 
  "invokeaction", 
  "observeproperty", "unobserveproperty", 
  "subscribeevent", "unsubscribeevent" } 
TdOperation;

interface URIVariables {
  maplike<DOMString, DOMString>;
};
dictionary InteractionOptions {
  UriVariables uriVariables;
  WotListener listener;  // not for all ops
};

callback WotListener = void(any data);
```

If we "relax" a bit the above and factor out `op`, then we'd have
```javascript
[Constructor(ThingDescription td), SecureContext, Exposed=(Window,Worker)]
interface ConsumedThing {
  Promise<any> read(DOMString propertyName, optional PropertyOptions options);
  Promise<any> write(DOMString propertyName, any value, optional PropertyOptions options);
  Promise<any> invoke(DOMString actionName, optional ActionOptions options);
  Promise<DOMString> observe(DOMString name, optional InteractionOptions options);
  Promise<void> unobserve(DOMString id);
  Promise<DOMString> subscribe(DOMString name, WotListener listener, 
                                                      optional InteractionOptions options);
  Promise<void> unsubscribe(DOMString id);
  ThingDescription td();
};
callback WotListener = void(any data);

interface URIVariables {
  maplike<DOMString, DOMString>;
};
dictionary InteractionOptions {
  UriVariables uriVariables;
};

enum {"single", "multiple", "all" } PropertyInteractionType;
dictionary PropertyOptions: InteractionOptions {
  PropertyInteractionType type = "single";
};

interface ActionParameters {
  maplike<DOMString, any>;
};
dictionary ActionOptions: InteractionOptions {
  ActionParameters params;
};
```

We could also factor out `PropertyInteractionType` and have an extension of the current API with options, but I'd prefer simpler signatures (like `read()`, `readAll()`, `readMultiple()`, `invoke()`, `observe()`, `subscribe()`, since it's still unanimous, e.g. one can only read Properties, not Events). 

If we stick to the full TD op names to be closer to the TD spec, then I'd prefer going the `op` as a parameter route since that design is closer to the TD spec.

**Comment by danielpeintner** [comment]
I would stick with what we have so far with the only change that `optional any params` needs to be added where it is currently missing.

**Comment by zolkis** [comment]
It is not clear whether besides `uriVariables` (and `op` that is selected by the method name currently) aren't there other options to be exposed as well, for instance:
- `subprotocol`
- `scope` (one of scopes)
- response (actually `expectedResponse`).

Should we design the previously used `InteractionOptions` with this in mind, i.e. it would have a property named `uriVariables`, or `InteractionOptions` should itself be the `uriVariables`?
If we ever expand `InteractionOptions`, then we need the explicit design.

**Comment by zolkis** [comment]
Also, it is a question whether InteractionOptions apply for Properties, or also for Events (any use case examples there how it should work?).

**Comment by zolkis** [comment]
We have the problem that URI variables are not properly defined in the TD spec. If we need to go and specify a map of DataSchema (as stated in the TD), we have opened Pandora's box, blowing up the spec several times in size and it's off-topic. So URI variables need to be defined in a different specification than WoT Scripting.

Using raw objects defined elsewhere is not considered a good practice in web specs. But we (almost) do the same with the TD (represented as object).

If we don't find a solution for this, we should represent URI variables (and TDs) as strings, then another spec should describe how to produce, parse and validate them.

**Comment by zolkis** [comment]
Actually, thinking it over again, I don't see much risk in NOT supporting URI template variables at Scripting API level. It should always be possible to write a TD that uses Actions for interactions that need URI variables, including events/webhook example in the TD spec. Exposing URI variables at Property and Event level reveals bad design and those TDs should be rewritten IMHO. Currently it's a mess.

**Comment by danielpeintner** [comment]
Does the last comment mean we would add an optional parameter to almost any method named `options` or so where at the moment uriVariables is a possible candidate?

**Comment by zolkis** [comment]
The last comment is a rant. The commit with the options is in #185
