### ISSUE TITLE
getTD() method instead of td attribute

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#184]
We should consider changing the td from readonly attribute to a method, since it is more flexible for implementations

**Comment by zolkis** [comment]
Hmm, on the other hand, the attribute contains the exact same object that was created while constructing the ConsumedThing object (i.e. from expanding the init dict) so it seemed simpler to expose it as attribute.

Of course that does not stop us from the possibility to expose it through a method (in fact the attribute will have a getter method).

However, IIRC we went for attribute for the reason that it looks better in the examples to say 
```javascript
thing.td.properties["temperature"]
``` 
than to say 
```javascript
thing.getThingDescription().properties["temperature"]
``` 
and developer convenience is higher priority than implementation benefits (unless there are good reasons why an implementation can't do something in the getter and needs an explicit fetch function).

**Comment by zolkis** [comment]
That being said, one could also argue that application scripts would more typically or more frequently use the ConsumedThing interface (read/write properties, invoke actions, handle events) than directly explore the TD, therefore we have low friction on whether we use `thing.td()` or `thing.td`.

About the name, `getThingDescription()` would be the most canonical, `getTD()` a mix, `.td()` a bit too laconic (but least difference from the current `.td`). Any suggestions?

**Comment by zolkis** [comment]
Be aware that if we make `td()` or `getTD()` a function, we need to add an internal slot for `td` anyway, so the algorithms would work. This makes the spec more complex than with handling it as attribute.

**Comment by danielpeintner** [comment]
I don't have a strong opinion but my preference is `getTD()` (and not `td()`).

**Comment by zolkis** [comment]
I already hear reviewers saying `getTD()` is not a good/descriptive name, so it has to be `getThingDescription()` then.

**Comment by danielpeintner** [comment]
to be honest both (`getTD()` and `getThingDescription()`) seem fine to me

**Comment by zolkis** [comment]
OK. Amended commit on the way.
