### ISSUE TITLE
setPropertyWriteHandler() gives impression that all properties will be writeable

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#199]
In the explanation of [setPropertyWriteHandler()](https://w3c.github.io/wot-scripting-api/#the-setpropertywritehandler-method), it says:
> If no write handler is initialized for any given Property, implementations SHOULD implement default property update and notifying observers on change, based on the Thing Description. 

I think that it should be rather:
> If no write handler is initialized for any given _writeable (or non readOnly)_ Property, implementations SHOULD implement default property update and notifying observers on change, based on the Thing Description. 

Otherwise, it gives the impression that a Scripting API implementer should add a write handler for properties that are readOnly as well.

**Comment by zolkis** [comment]
Note that a write handler will have access to low level HW APIs, so it is supposed to define the write behavior at its own will, including what errors to return. If implementations trust the app to provide write handler for positive use cases, I don't see why they should not trust apps for providing implementation for negative use cases as well.

In my view, even for readonly Properties, any ExposedThing script (app) implementation could specify a write handler.
If it does not, then a default handler is assigned by the implementation.
If it is defined, it is supposed to define the behavior of how write is rejected and should be executed by the implementation.

**Comment by egekorkan** [comment]
> If it does not, then a default handler is assigned by the implementation.

I totally agree with this, but the current explanation gives the impression that the default handler will update the property and then also notify the observers about the change, even if it is not writeable. 
This means that if I write a script where I want a property to be readOnly for sure, there can be a Scripting API implementation that still does an update.

**Comment by zolkis** [comment]
OK, so we should explain the exact behavior in more details.
