### ISSUE TITLE
ThingFilter server attribute - Issue 50 from w3c/wot

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#226]
Let's continue the discussion from: https://github.com/w3c/wot/issues/50 here. I couldn't be sure if all the comments are considered but somewhat yes?

**Comment by relu91** [comment]
Thanks, Ege, it seems quite outdated but it could help the discussion about #222.

**Comment by relu91** [comment]
Please use #222 as follow up, or re-open it if needed.
