### ISSUE TITLE
Event handling - Issue 235 from w3c/wot

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#228]
Coming from https://github.com/w3c/wot/issues/235

I think that event handling is properly specified in the Scripting API, however, the initial comment says that "Event handling should be harmonized with the devices and protocols WG". Once I look there (https://www.w3.org/TR/generic-sensor/#the-sensor-interface) I see that our Scripting API is not harmonized with it. I don't think that it should be but would an explanation needed on why it is not the case? (Someone can ask about this upon going for publication)

**Comment by danielpeintner** [comment]
Scripting Call 2020-10-19
*old* issue, discussed and explored a lot which lead to the current solution --> Closing
