### ISSUE TITLE
Should we use affordance instead of interaction?

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#241]
Throughout the document, we often use *WoT interaction* referring to *Properties/Actions/Events*. Should we changed to *WoT affordance*? 

Derived from #239

**Comment by egekorkan** [comment]
Yes we should

**Comment by zolkis** [comment]
For JS developers the term "interaction" is intelligible, whereas "affordance" is a more special term, mainly for WoT-insiders...

**Comment by danielpeintner** [comment]
> We could make an editor's note perhaps to say that "interaction" in this document matches to "interaction affordance" in the TD spec.

Or the other way around. Stick with WoT terminology "affordance" and given a hint to JS developers.

**Comment by danielpeintner** [comment]
Scripting Call  Aug 31: 
* add Note explaining the relation between Scripting "interaction" and TD "affordance"
