### ISSUE TITLE
ReadHandler description is not completely correct 

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#243]
For reference:
https://github.com/w3c/wot-scripting-api/blob/75dc2b2ab80b99cf586fed57c716f184dc7c26fb/index.html#L1832-L1842

The description says that the *ReadHandler* may reject if the property is not found. However, this callback does not know the property associated with it. Therefore, it might be difficult to reject if the property is not found. 

Derived from #239

**Comment by egekorkan** [comment]
I think it should be removed, the same check exists also for setPropertyReadHandler

**Comment by zolkis** [comment]
The behaviour should be stated in the algorithms, the text here just states the purpose.

But that purpose is defined by the algorithms of the `set...Handler()` methods, and in those actually reject is called when the property is not found.
