### ISSUE TITLE
Semplify Consumed thing example

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#245]
As we already discussed the most commonly used interface for reading from a *WoT Runtime* would be the `value` function. I'd simplify the following code example:
https://github.com/w3c/wot-scripting-api/blob/75dc2b2ab80b99cf586fed57c716f184dc7c26fb/index.html#L1670-L1724

I'd remove the `parseData` function and leave only calls to the value function. We may add separate examples were to describe and show advance usage of the `InteractionOutput` interface (i.e. error handling and streaming reading).

**Comment by zolkis** [comment]
Agree, this is quite old code snippet. Go ahead and update :)

**Comment by danielpeintner** [comment]
FYI: there is a bug in parseData function

```
  try {
    value = await response.value();
  catch(err) {
```

the last line needs to start with `}`

**Comment by relu91** [comment]
@zolkis I think this can be closed now. Feel free to reopen it if I missed something :)
