### ISSUE TITLE
Isolation of scripts / sandbox and access to outside

### ISSUE THREAD

**Issue by h0ru5** [w3c/wot-scripting-api#25]
This issue is opened to capture the [outcomes of last F2F](https://www.w3.org/2017/05/15-19-wot-minutes.html#wednesday-item08) and continue the discussion.

points discussed and concluded:

* scripts have a security context with implications on their level of access 
* scripts run in a script execution context that can be used isolates groups of scripts and things
* runtimes CAN have one single or multiple script execution contexts
* we should define the interrelation between the origin (uri) and the execution context
* we should formulate the guarantees/contract that a script developer can rely on (single-threaded execution etc.)
* when starting a script, the runtime needs to know in which context it runs
* origin / context does not relate "1:1" to the browser world
 * we conclude on encouraging encapsulating functionality (such as accessing the system) into thing interfaces
* such local things are accessed in the script just like remote things (discovery & client API etc.)

**Comment by mmccool** [comment]
We should also review/contribute to this in the Security TF.

**Comment by zolkis** [comment]
The [Security doc](https://www.w3.org/TR/wot-security/) handles some of this.
Some of the suggestions from the opening comment need to be discussed in the next charter.
