### ISSUE TITLE
Stale TD mitigation outdated (?)

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#252]
Section [10.2.3 Stale TD Security Risk](https://w3c.github.io/wot-scripting-api/#sec-security-consideration-script-stale-td) says:
> Mitigation:
> Scripts should use this API to subscribe for notifications on TD changes and do not rely on TD values to remain persistent.

However, none of the current specification documents mention about mechanisms for TD notifications. On the contrary, it seems that we are going towards immutable Thing Descriptions.

**Comment by zolkis** [comment]
Pretty old threat & mitigation, it seems, let's update.

**Comment by danielpeintner** [comment]
Call 2020/01/02
Seems we can remove this section. There is no way to subscribe to TD changes any longer.

Note: Should revisit whole section 
@danielpeintner to propose PR
