### ISSUE TITLE
Update open issues section

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#253]
The [Open issues](https://w3c.github.io/wot-scripting-api/#openissues) feels a little bit outdated. For example (maybe related to #252 ): 

> An explicit API for adding and removing Property, Action and Event definitions on ExposedThing (it was present in earlier versions, but removed for complexity and a simpler way to do it.

As far as I know, this issue has been already resolved and explained in the other sections of the document. I'd also add there the discussion about `writeMultiple` and `readMultiple`.

**Comment by zolkis** [comment]
Maybe we could delete the whole section. Open issues can be checked from github, for which we have a link to.

**Comment by egekorkan** [comment]
I would also vote for deleting the section :)

**Comment by danielpeintner** [comment]
Closed by PR https://github.com/w3c/wot-scripting-api/pull/254
