### ISSUE TITLE
Potentially insufficient error handling for emitEvent()

### ISSUE THREAD

**Issue by jak0bw** [w3c/wot-scripting-api#256]
Related to #237 but on the sender side. 

When emitting an event §8.27 The emitEvent() method does only define a SecurityError and a NotFoundError, but does not define an error if the emit fails due to another, perhaps technical problem. Consider similar to #237 a sender who wants to emit an event to the configured, but currently offline mqtt broker. This probably results in an error on the protocol level, but is never communicated to the application level. EmitEvent() probably needs a similar definition as:
> §7.13 The invokeAction() method 
> 8. If the request fails locally or returns an error over the network, reject promise with the error received from the Protocol Bindings and abort these steps.

**Comment by zolkis** [comment]
The PR is not fixing the issue. Will leave the discussion summary from the Scripting call on 28.9.2020.

**Comment by zolkis** [comment]
> 1. The ExposedThing implemention script should get an error when a notification fails (that is, local delivery). This should be standardized. I can make another PR for this.

The proposed solution for this one would be to return a Promise by emitEvent(), which might reject with an error when the event notification is not successful. This is a trivial change.

> 2. If there is protocol (binding) support for conveying a subscription error to the clients, then it could be signaled at the clients through the ErrorListener callback.

For this one the Scripting API already has coverage via `ErrorListener`, though the exact mechanism is encapsulated by implementations and might differ binding from binding.

> 4. There was a point about handling errors at the client side for subscriptions (both via Promise and the error callback).

This is still outstanding and could be discussed in a separate issue. One (quite trivial) solution would be to revert to the separate `subscribe()`-`unsubscribe()` and `observe()`-`unobserve()` pair, which also align better with the TD spec. On subscription, a subscription id could be returned to ease subscription management.

**Comment by danielpeintner** [comment]
see https://github.com/w3c/wot-scripting-api/pull/269

**Comment by danielpeintner** [comment]
Scripting Call 2020-10-19.
Closing...

TD related issue "defining error" <Link>

**Comment by relu91** [comment]
I am closing this one, the issue was solved and the last open point it is being tracked on the following issues:
- https://github.com/w3c/wot-thing-description/issues/303 
- https://github.com/w3c/wot-thing-description/issues/617
- https://github.com/w3c/wot-scripting-api/issues/200
- https://github.com/w3c/wot-discovery/pull/52 (related PR from the discovery task force)
