### ISSUE TITLE
policies of security enforcement in the scripting runtime

### ISSUE THREAD

**Issue by h0ru5** [w3c/wot-scripting-api#26]
as identified in the webconf on 29-05-2017:

> We should discuss and propose implicit policies and mechanisms to specify explicit policies to allow or deny interactions based on script's context resp. URI (cross-TF topic w/ security)

This basically refers to mechanisms on how a WoT runtime decides whether to allow or deny a request from a script running in a certain security context (see #25 ).

This also refers to  whether we can identify implicit policies (such as e.g. the same-origin-policy in web UAs) and/or whether we should provide mechanisms on how to explicitly state such policies.

**Comment by mmccool** [comment]
Noted; I will mention in the Security TF meeting.   Actually, it would be good to have a tag for security-oriented feature proposals to bring them to the attention of the Security TF.

**Comment by zolkis** [comment]
Mostly handled by the [Security Recommendations](https://www.w3.org/TR/wot-security/)
