### ISSUE TITLE
WoT network interface definition missing in Architecture 

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#273]
While working on #272, I found that in section 11 we say that the Architecture document defines a list of terms. Between those there is WoT network interface, but I can't find it in the Archicture [section](https://www.w3.org/TR/wot-architecture/#terminology). Should we change it? or remove it?

**Comment by zolkis** [comment]
The term is simply `WoT interface` nowadays.

**Comment by danielpeintner** [comment]
Scripting Call 2020-10-19:
Remove any appearance of "WoT network interface" and replace it with "WoT Interface".
Keep definition as is and remove reference to architecture document.

**Comment by relu91** [comment]
Fixed in #279. Leave WoT network Interface but define it as a synonym of WoT Interface.
