### ISSUE TITLE
Remove ConsumedThing inheritance in ExposedThing

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#281]
and clarify the "local client" optimizations in `ExposedThing`. 

Coming from https://github.com/eclipse/thingweb.node-wot/issues/333 

One solution would be to resolve `expose()` with a `ConsumedThing` with local bindings (for maintaining convenience), instead of `ExposedThing` extending `ConsumedThing`, which created confusions.

**Comment by danielpeintner** [comment]
It looks like we do have consensus for point 1. and 2. proposed [here](https://github.com/eclipse/thingweb.node-wot/issues/333#issuecomment-724008242)

Let's settle this discussion (and our thoughts) a bit more and go for it if no more concerns pop up

**Comment by zolkis** [comment]
Fixed by #280
