### ISSUE TITLE
Partial TD validation

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#287]
The scripting API [`produce()`](https://w3c.github.io/wot-scripting-api/#the-produce-method) methods allows for passing a TD fragment argument. It is essentially a init dictionary of a TD.

We might want to have a proper validation of this TD fragment argument.
The idea is to use the existing [JSON Schema](https://w3c.github.io/wot-thing-description/#json-schema-for-validation) form the ThingDescription document with the only difference that all `"required": { ... }` keywords are pruned. 

Question: difference between TD model and TD fragment used in scripting.
see [related discussion for TD model](https://github.com/w3c/wot-architecture/issues/574#issuecomment-757925291).

**Comment by relu91** [comment]
I think we should rename this: "Partial TD validation". TD fragments are more relevant for TDD search answers.

**Comment by danielpeintner** [comment]
Call 2021-01-18: @relu91 volunteered to work on a PR providing an algorithm to validate partial TD input (e.g., by re-using the [JSON schema used in the TD spec](https://w3c.github.io/wot-thing-description/#json-schema-for-validation))
