### ISSUE TITLE
PropertyReadHandler properly defined?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#290]
The [ExposedThing interface](https://w3c.github.io/wot-scripting-api/#the-exposedthing-interface) defines the `PropertyReadHandler` as follows

```
callback PropertyReadHandler = Promise<any>(
        optional InteractionOptions options = null);
```

while  the `ActionHandler` is defined as follows.

```
callback ActionHandler = Promise<InteractionInput>(
        InteractionOutput params,
        optional InteractionOptions options = null);
```

Shouldn't `PropertyReadHandler` be also in the same fashion? Replacing `any` with `InteractionInput`?

```
callback PropertyReadHandler = Promise<InteractionInput>(
        optional InteractionOptions options = null);
```

**Comment by relu91** [comment]
Yes, it should be fixed.

**Comment by danielpeintner** [comment]
Thanks for the feedback. Let's quickly discuss it in our next call.
If we all agree I will provide a PR...

**Comment by danielpeintner** [comment]
resolved by https://github.com/w3c/wot-scripting-api/pull/291
