### ISSUE TITLE
Does PropertyMap need to be different for reading and writing a value?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#293]
The type [`PropertyMap`](https://www.w3.org/TR/wot-scripting-api/#dom-propertymap) is defined as a map of property names as strings to a value that the Property can take.

The `PropertyMap` is used for the following calls.
* Promise<PropertyMap> readAllProperties(optional InteractionOptions options = null);
*  Promise<PropertyMap> readMultipleProperties(sequence<DOMString> propertyNames, optional InteractionOptions options = null);
* Promise<undefined> writeMultipleProperties(PropertyMap valueMap, optional InteractionOptions options = null);

I believe the _value_ part of the map needs to differ for reading and writing. Am I wrong?
* for reading it needs to be of type `InteractionOutput` while 
* for writing it needs to be of type `InteractionInput`

Shall we specify it or have to different kinds of maps (`PropertyMapOutput` and `PropertyMapInput`)?

**Comment by zolkis** [comment]
Yes, in practice the values in PropertyMap should follow that pattern. However, we can specify the exact expected types in the algorithms. In the xxxMultipleProperties methods we just use property bags, as sets.

However, we could formalize also in Web IDL. Not sure if it's worth, but we could do it.

**Comment by danielpeintner** [comment]
Scripting Call 2021-02-22
* @zolkis points to https://heycam.github.io/webidl/#dfn-maplike-declaration also 
  * will propose PR
* diverge in TypeScript?

**Comment by relu91** [comment]
I think in TS it could be represented simply as:
```ts
type PropertyReadMap = Map<string,InteractionOutput>;
type PropertyWriteMap = Map<string,InteractionOutput>;
```

As the maplike documentation explicitly says that for: 
> ECMAScript language binding the API for interacting with the map entries is similar to that available on ECMAScript Map objects. If the readonly keyword is used, this includes entries, forEach, get, has, keys, values, @@iterator methods, and a size getter. For read–write maplikes, it also includes clear, delete, and set methods.

And Map class in TS represents the ES6 Map.

**Comment by zolkis** [comment]
> ```javascript
> type PropertyWriteMap = Map<string,InteractionOutput>;
> ```

I think it should be
```javascript
type PropertyWriteMap = Map<string,InteractionInput>;
```

**Comment by relu91** [comment]
yes exactly thanks, it just already fixed in the new TS file. 

https://github.com/relu91/wot-scripting-api/blob/3f62f023a29114c8f2d2e291a5b5a59c9356a09d/typescript/index.d.ts#L183-L184

Closing the issue.
