### ISSUE TITLE
Should value function return DataSchemaValue?

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#294]
If we keep the current API design I think that we should change the return type of the value function in the [WebIDL](https://www.w3.org/TR/wot-scripting-api/#dom-interactionoutput). Currently, it returns `Promise<any>` but it would be more correct to use the newly defined [DataSchemaValue](https://www.w3.org/TR/wot-scripting-api/#dom-dataschemavalue).

**Comment by danielpeintner** [comment]
I agree!

... even though `DataSchemaValue` is any

**Comment by danielpeintner** [comment]
I proposed a fix, see https://github.com/w3c/wot-scripting-api/pull/295

Please have a look.

**Comment by danielpeintner** [comment]
fixed by https://github.com/w3c/wot-scripting-api/pull/295
