### ISSUE TITLE
TypeScript - Type DataSchemaValue circularly references itself

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#301]
After merging https://github.com/w3c/wot-scripting-api/pull/297 and trying to update node-wot I run into the following build issue.

```
lerna ERR! npm run build exited 2 in '@node-wot/binding-opcua'
lerna ERR! npm run build stdout:

> @node-wot/binding-opcua@0.8.0 build C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua
> tsc

../core/node_modules/wot-typescript-definitions/index.d.ts(80,17): error TS2456: Type alias 'DataSchemaValue' circularly references itself.
```

Not sure if it is actually a regression like mentioned [here](https://github.com/microsoft/TypeScript/issues/37649).

**Comment by relu91** [comment]
Can we upgrade the tsc version for OPC UA? I also had to upgrade tsc for the core to 4.0.0. Updating dev dependencies should not be a big problem. What do you think?

**Comment by danielpeintner** [comment]
I updated "typescript" from "3.6.3" to "3.9.2" and it resolved the problem.

I did try the latest version "4.1.3" but many side-issues popped up... maybe no big deal to find the causes but i thought it is safer to stick with 3.x

**Comment by danielpeintner** [comment]
Scripting Call 2021-08-02
issue seems to be solved for *newer* TS versions (by upgrading)
