### ISSUE TITLE
ActionHandler returning InteractionInput always

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#302]
`PropertyReadHandler` and `ActionHandler` are the same when it comes to the return value (returning `Promise<InteractionInput>`).

```
callback PropertyReadHandler = Promise<InteractionInput>(
        optional InteractionOptions options = null);

callback ActionHandler = Promise<InteractionInput>(
        InteractionOutput params,
        optional InteractionOptions options = null);
```

I wonder whether this is correct given propertyRead always returns a value and actions do not always return anything.
Shouldn't the return statement for `ActionHandler` be as follows?
`
Promise<undefined | InteractionInput>`

**Comment by relu91** [comment]
Good point actually. +1 from my side

**Comment by zolkis** [comment]
We don't need it, since an object can be `null` and `undefined`. Describe in prose that it can be `undefined`.

**Comment by danielpeintner** [comment]
Scripting Call 2021-02-22
* @zolkis see comment above
* @relu91 do the suggested changes in TS only
* @danielpeintner check prose

**Comment by relu91** [comment]
BTW the TS part was addressed in this PR: https://github.com/w3c/wot-scripting-api/pull/307

**Comment by danielpeintner** [comment]
I think we can close the issue, right?
* WebIDL is clear that it can be null
* TS was fixed

**Comment by danielpeintner** [comment]
Scripting Call 2021-03-08, Agreed to close
