### ISSUE TITLE
Management Thing - update verb

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-scripting-api#33]
Should there be an "update" verb for ManagementThing?   The "install" verb could be used to create new Things, while "update" would update the script on an existing thing.

**Comment by danielpeintner** [comment]
Is still an open issue? We do have information about ManagerThing [here](https://github.com/w3c/wot-scripting-api/tree/master/applications/script-manager) but there is no strong focus/work on it right now...

**Comment by zolkis** [comment]
This issue concerns the vocabulary there. It's still open.

**Comment by zolkis** [comment]
Out of scope in the current charter.
