### ISSUE TITLE
Description for labels

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#336]
https://github.com/w3c/wot-scripting-api/labels

describe what it is about ...

**Comment by danielpeintner** [comment]
Please find below a possible description for each label:

* bug: an error, flaw or fault in the specification that causes misunderstandings and/or incorrect/unexpected results

* discovery: relates to discovery and/or relates to joint work/discussions with the discovery task force

* Editorial: topics purely about editing the document (i.e., typos)

* enhancement: thoughts and ideas about possible improvements

* F2F: topics related to Face-to-Face meetings

* for next iteration: planned or postponed topics for the future

* propose closing: solutions exists and labelled as to be closed soon

* question: any generic question and/or comment

* Runtime: runtime-related topics

* Script Management: how to manage/control scripts

* use case: describes a scenario that may be useful for technical decisions

* validation: relates to how to conform to a given set of rules (e.g., data validation, conformance)


Any thought/update/proposal?

**Comment by danielpeintner** [comment]
@zolkis others?
Any opinion?

**Comment by zolkis** [comment]
IMHO we don't need "other": just don't put a label if we don't have one.

**Comment by danielpeintner** [comment]
> IMHO we don't need "other": just don't put a label if we don't have one.

Mhh, I did not have any plan to have an "other" label. My question is rather whether the description for the ones mentioned in https://github.com/w3c/wot-scripting-api/issues/336#issuecomment-914966010 is okay.
If so, I would apply them. At the moment there is no proper description at all.

**Comment by danielpeintner** [comment]
As discussed in the scripting call today I applied the descriptions for the [labels](https://github.com/w3c/wot-scripting-api/labels).
