### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-scripting-api#34]
Should there be a debugging interface?   Could be part of ManagementThing interface (or not; to discuss).
Of course could be a runtime-specific API (which could be language-dependent), my thought is there could be some language-independent debugging interface that for instance, could allow watching events, property updates, etc. that don't depend on language.

The argument for combining it with the Management thing is that the same security level is needed, and also debugging is typically used in software development where there will also be a need to update scripts, functionality already supported by the Management thing.   

The reason also to have a "front door" debugging interface would be that it would provide a way to debug "services" that work across multiple runtimes from different manufacturers and maybe using different languages internally.

**Comment by danielpeintner** [comment]
My naive view on a "debugging interface" is that we do not need it in Scripting API. Moreover, I would not restrict debugging to scripting only.

In my thinking a thing that runs in debugging mode simply offers _additional_ observable properties or allows for registering additional handlers and such.
Security aspects should be handled with the same techniques as any other thing interaction (with a higher security level of course).

Is my view too simple?

**Comment by mmccool** [comment]
The debugging interface would not be "in" the Scripting API but would be a service (like the Management Thing) that would provide external access (breakpoints, watching, etc).   It could be based on the Chrome debugging API which would allow the use of the Chrome debugger.   The reason for standardizing it would be to use a single debugger for multiple runtimes from different vendors.

That said, I think it is a second-order issue.

**Comment by mmccool** [comment]
We have decided to not consider this for now.

**Comment by danielpeintner** [comment]
Shall we keep such issues open? I recommend creating a dedicated label such as "ToRevisit" fot such issues and get back to it later...

**Comment by zolkis** [comment]
This is not for the API spec, but the auxiliary documents describing applications (like Thing Directory, Thing management, synchronization etc). We need to discuss in the call how to handle them. We could keep it open still. Once we address this in the auxiliary docs, we can close it.

**Comment by zolkis** [comment]
Out of scope for the API spec itself.
