### ISSUE TITLE
Reference terminology section of the architecture specification

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-scripting-api#342]
The terminology section comes very late in the document. Typically terminology is introduced in the beginning.

See for example the protocol binding template specification.

Please consider moving most of the definitions to the architecture terminology section to simplify / harmonize among the WoT specification family and move the terminology chapter to sectinon 3.

**Comment by danielpeintner** [comment]
It seems we should move the "Terminology" section to chapter 4 to be aligned with other documents.
*  Introduction
*  Use Cases (specific to Scripting)
* Conformance
*  Terminology

**Comment by danielpeintner** [comment]
Scripting API 2021-12-06
This issue can be closed since terminology has been moved and cleaned-up.

Created associated issue for "Uses cases" topics, see 
https://github.com/w3c/wot-scripting-api/issues/355
