### ISSUE TITLE
LinkChecker Errors

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#348]
W3C Link Checker reports 6 errors in this spec: https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fwot-scripting-api&hide_type=all&depth=&check=Check

**Comment by danielpeintner** [comment]
Some errors are false, see

```
error Line: 3948 https://w3c.github.io/wot-thing-description/
    Status: 200 OK
```

Some of the links to this resource point to broken URI fragments (such as index.html#fragment).  Broken fragments:

*  https://w3c.github.io/wot-thing-description/#securityscheme (line 3948)
*  https://w3c.github.io/wot-thing-description/#nosecurityscheme (line 3948)
