### ISSUE TITLE
Management Thing - verb semantics clarification

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-scripting-api#35]
Would be useful to clarify the meanings of the verbs "run" and "start" for the Management Thing.   In particular, are they persistent?   Are they like "enable/disable" for systemd services?   If not, may want verbs that distinguish whether or not things are persistent.   Might be useful to look at/adopt verbs used to manage systemd services.

**Comment by zolkis** [comment]
Out of scope in the current charter.
