### ISSUE TITLE
Next charter topics

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#352]
We should try collecting topics we want to work on in the next charter (besides keeping the work up with being TD-aligned).

Some initial ideas
* *new* op value support for `cancelaction`, `queryaction`, ...
* TD canonicalization / TD signing
* TD profile support
* Management API (different API / document?)
  - orchestration
  - setting up security
* Discovery

**Comment by egekorkan** [comment]
The whole hypermedia and complex actions topic would be nice as well. There were multiple proposals in the TD spec but from the Scripting level, they will all look the same so work can be started here I think.

**Comment by relu91** [comment]
As a task force we may focus our forces trying to bring the API to [Project Fugu](https://www.chromium.org/teams/web-capabilities-fugu) I know that in previous years there was not really a big interest from the community, but it may be worth trying it again.

**Comment by egekorkan** [comment]
Look pretty nice actually. Was the lacking interest from the WoT community side or from Fugu?

**Comment by zolkis** [comment]
I can ask - but we need to discuss a focused area (for instance limiting to https only), and well defined use cases, with examples why would it be useful in Fugu.

**Comment by danielpeintner** [comment]
_New_ topic? : Ways to retrieve historical data (timeseries data). 
Should this be part of the Scripting API or build on top (or outside) of it?

**Comment by relu91** [comment]
Call 15/01:
- @relu91 will verify if there are already issues describing the todo items, and if so add the proposed closing label.

**Comment by relu91** [comment]
Linking issues:
- new op value support for `cancelaction`, `queryaction` : https://github.com/w3c/wot-scripting-api/issues/335
- Management APIs: https://github.com/w3c/wot-scripting-api/issues/298
- Discovery: we have a [label](https://github.com/w3c/wot-scripting-api/issues?q=label%3Adiscovery+) for this. 
- Profiles #531
- TD canonicalization / TD signing:  https://github.com/w3c/wot-scripting-api/issues/532
