### ISSUE TITLE
Dynamic Management Things - Management TD for each installed script

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-scripting-api#36]
Assume that each script is, essentially, a Managed Thing. When installed and run, the script makes one or more instances of Exposed Thing or Consumed Thing that are then managed, at a high level, through the Management Thing. 

Consider dynamically creating management resources and a Management TD for each installed script. The "handle", instead of a UUID, would become a pointer to the Management TD for the installed script.

URLs in the properties/actions of the Management TD would point to the management actions of the new script and would be used to manage the life cycle of the script, as per the existing proposals.

A Management TD would have separate permissions from the TDs of the Exposed Things. The Manager role client would typically only have permission for the Management Things and resources.

A Management TD would expose the life cycle state properties and controls for the script, e.g. running, stopped, error, start, stop, uninstall, etc.

If a script is uninstalled permanently, its Management TD may be removed.

The central Management Thing would be used to (pre)install a script to make its Management TD available, after which the script would be managed through its management TD. The central Management TD might also have some controls and actions for the runtime.

**Comment by farshadahmadi** [comment]
Hi,

I have several questions:

1. @mjkoster proposes a central Management Thing that creates a Management TD for each installed script. Thereafter, all management actions should be done via the associated Management Thing. However, the proposed **WoT Script Manager Thing** [here](https://github.com/w3c/wot-scripting-api/tree/master/applications/script-manager) by @zolkis only considers a central Management Thing to manage the lifecycle of all scripts. Is there any consensus which way to go?

2. The Node.js reference implementation, [node-wot](https://github.com/thingweb/node-wot), includes only _runScript_ action in the Servient TD to run (aka start) scripts. Is this Servient TD going to play the role of central Management Thing?

3. Somehow not relevant question to this topic: What is the most comprehensive Node.js reference implementation of W3C WoT?

**Comment by zolkis** [comment]
Script management discussion has been on hold for a while because:
- the "manager Thing" is considered a (privileged) WoT application, not part of the WoT Runtime
- script deployment/management (in general, provisioning) is out of scope for the Scripting API in the charter, however, I personally believe that it would be important to establish at least some best practices/examples there.
- currently we are focusing on getting the TD and Scripting API right, and only then will deal with deployment.

The [node-wot](https://github.com/thingweb/node-wot) project is the reference implementation.

**Comment by zolkis** [comment]
Since this is out of scope currently, I close this issue. If future work will be chartered for this, we'll retake there.
