### ISSUE TITLE
Consider moving terminology definition to WoT Architecture

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-scripting-api#360]
Please consider, if moving this terminology entry to the architecture.

WoT Interaction is a synonym for Interaction Affordance. An Interaction Affordance (or shortly, affordance) is the term used in [WOT-TD] when referring to Thing capabilities, as explained in TD issue 282. However, this term is not well understood outside the TD semantic context. Hence for the sake of readability, this document will use the previous term WoT interaction or, simply, interaction instead.

**Comment by zolkis** [comment]
It is a document-local term, tailored to the expected developer audience not necessarily familiar with semantically fluffy terms such as "interaction affordance". But the term "interaction" is widely understood, and "WoT interaction" gives it a more specific context.  

If we want to use it as a WoT-global term in Architecture, the editors of the Architecture spec can add that after the necessary group discussion. When the term becomes WoT-global, Scripting spec can refer to that.

So the plan is the following:
1. discuss in main call
2. pull in the term in Architecture
3. change the Scripting spec.

My note: for the sake of readability (for not having to leave the document), local definitions or editor's notes should be still allowed.

**Comment by danielpeintner** [comment]
Scripting API 2022-01-10

@mlagally do you agree with @zolkis ?

**Comment by relu91** [comment]
Call 12/12:
- @zolkis we considered the changes 
- @relu91 I think the definition belongs to our document because is very specific
- @danielpeintner agree. 
- @mlagally please re-open if you feel otherwise.
