### ISSUE TITLE
Should we publish TS types also for `ThingModel`?

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#361]
Together with its JSON schema?

**Comment by danielpeintner** [comment]
We can, since it may be useful for implementations.

On the other hand, we do not even reference "Thing Model" in the Scripting API.
I think it makes even more sense once we make use of Thing Model in our document.

**Comment by danielpeintner** [comment]
Scripting API Call 2022-01-10

Fine by scripting task force to publish it as yet another TS file
* add *short* explainer what it is, point to https://w3c.github.io/wot-thing-description/#thing-model etc

**Comment by relu91** [comment]
closing (?)
