### ISSUE TITLE
Discovery API - Alternatives

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-scripting-api#364]
When trying to implement the current discovery API I got the impression that its current design could be simplified by using a structure similar to the subscription/observation of events/properties. In particular, I had problems with implementing step two of the `next()` method:

> If the active property is true, wait until the discovery results internal slot is not empty.

Correct me if I am wrong, but it seemed to me as if this would only be possible by continuously checking the results, using a function like `setTimeout` or within a while loop (are there any implementation examples?). As this didn't seem that optimal to me, I tried out a callback based approach instead (similar to the `Subscription` interface and the `observeProperty`/`subscribeEvent` methods) which worked quite well so far.

I therefore wanted to suggest changing the signature of the `discover` method (or its potential successors  which are discussed in #222) to something like

```js
ThingDiscovery discover(DiscoveryListener listener, optional ThingFilter thingFilter = null);
```

where the `DiscoveryListener` function signature could look like the following:

```js
type DiscoveryListener = (thingDescription: ThingDescription) => void;
```

A minimal example could look like this:

```typescript
async function handleDiscovery(thingDescription: ThingDescription) {
    const consumedThing = await wot.consume(thingDescription);
    await consumedThing.invokeAction("foo");
}


wot.discover(handleDiscovery, { method: "direct", url: "coap://example.org/td" );
// Calling stop() can probably be omitted when the "direct" method is being used.
```

Here, the discovery process is initialized using the `direct` method. When a Thing Description has been retrieved successfully, the `handleDiscovery` function is called which consumes the TD and interacts with the Thing. If I am not mistaken, a similar approach (using a class called `Observable`) was already part of the specification some time ago but I still wanted to open this issue to discuss it as an alternative to the current `discover` method.

I am looking forward to your feedback!

**Comment by danielpeintner** [comment]
Scripting Call 2022-01-17
* collect pros and cons
* collect/write examples?
* align with other API style, subscription mechanism
* in case of same power: difficulty of implementing one or the other (e.g, blocking until *new* data is available)

**Comment by danielpeintner** [comment]
I have been thinking about this proposal and I like it. It well aligns with what we have for `Subscription`.

w.r.t. "power" I think one can achieve the same, e.g., 
* the discovery listener can `stop()`  if the desired result has been found

**Comment by JKRhb** [comment]
@danielpeintner Thank you for the feedback! 

> w.r.t. "power" I think one can achieve the same, e.g.,
> 
> * the discovery listener can `stop()`  if the desired result has been found

I would think so, too :) The only aspect that is probably not covered at the moment is pagination, but maybe this could be handled by adding additional parameters to the `DiscoveryListener` type definition. I guess we need an example to figure out how this use case could be handled.

Also, I had two ideas which could probably be further improvements to the approach from above. The first one would be to add a `stop()` callback parameter to the `DiscoveryListener` type definition, so that you can easily stop the discovery process once a certain condition is fulfilled. In the example below, the discovery would be stopped once a TD with a "foo" action is found. Maybe this approach could also be used to handle pagination in the background -- another "page" of TDs is only fetched from a directory if the discovery hasn't been cancelled by the user based on their own decision criteria.

The other idea I had was to turn the `start()` method of the `ThingDiscovery` object into a `restart()` method which could be used to reinitiate a discovery process. A separate `start()` method, so I thought, is probably not needed as the discovery process should start once the `ThingDiscovery` is initialized. Let me know what you think about this :)

```js
async function handleDiscovery(thingDescription: ThingDescription, stop: () => void) {
    if (thingDescription.actions.has("foo") {
        stop();
        const consumedThing = await wot.consume(thingDescription);
        await consumedThing.invokeAction("foo");
    }
}


const discovery = wot.discover(handleDiscovery, { method: "directoy", url: "coap://example.org/tdd" );
// ... some time passes, then the discovery process is started again
discovry.restart();
```

**Comment by danielpeintner** [comment]
Some questions...

> Also, I had two ideas which could probably be further improvements to the approach from above. The first one would be to add a `stop()` callback parameter to the `DiscoveryListener` type definition, so that you can easily stop the discovery process once a certain condition is fulfilled.

What is the difference of having `stop()` on `ThingDiscovery` ?
For subscriptions we have `stop()` also on `Subscription`.

> The other idea I had was to turn the `start()` method of the `ThingDiscovery` object into a `restart()` method which could be used to reinitiate a discovery process.

The alternative would be to create yet another `ThingDiscovery` OR is your assumption that `restart()` does not report again the matches it found before being stopped?

**Comment by JKRhb** [comment]
> What is the difference of having `stop()` on `ThingDiscovery` ?
> For subscriptions we have `stop()` also on `Subscription`.

The additional `stop()` would mostly be for convenience as (if I am not mistaken) you would need a construct like this to access the discovery object from the handler function:

```js
let discovery;
async function handleDiscovery(thingDescription: ThingDescription) {
    if (discovery != null) {
        discovery.stop();
    }
    ...
}

discovery = wot.discover(handleDiscovery, { ... );
```

The stop callback would be the same as the stop method, though. However, adding it as a callback would avoid the need for the null check and make stopping the process a bit more elegant.

> The alternative would be to create yet another `ThingDiscovery` OR is your assumption that `restart()` does not report again the matches it found before being stopped?

That would also be an option :) I thought that `restart()` would behave exactly as the initial discovery. This could be useful if you don't store the discovered TDs but perform a single action on them and then throw them away, for example. Or if you a common discovery pattern that will be restarted frequently.

**Comment by JKRhb** [comment]
I've been thinking about the `restart()` question a bit more and now arrived at the conclusion that the `start()` already behaves like a restart. As you might want to instantiate a `ThingDiscovery` object "manually" I think keeping the name `start()` could therefore make more sense.

**Comment by zolkis** [comment]
For API design here, let's also keep in mind browser event loop considerations. Probably known content, but anyway :).
[What the heck is the event loop anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ&list=PLz2VSmteYVgXba8XjpodjWSF7m1ZC2UBd) (youtube)
[In the loop](https://www.youtube.com/watch?v=cCOL7MC4Pl0&list=PLz2VSmteYVgXba8XjpodjWSF7m1ZC2UBd) (youtube)

**Comment by danielpeintner** [comment]
relates to https://github.com/w3c/wot-scripting-api/issues/222

**Comment by danielpeintner** [comment]
Scripting Call 2022-01-31

* @JKRhb creates PR for WebIDL 
* consecutively we discuss the updates

**Comment by zolkis** [comment]
A possible variant for a callback based discovery API uses the [Subscription ](https://w3c.github.io/wot-scripting-api/#dom-subscription) object, that already has an `active` flag and a `stop()` method that can also accept interaction options.  
However, the algorithms should have steps on how exactly the Subscription should be used.

```js
callback DiscoveryHandler = undefined(ThingDescription);

partial namespace WOT {
  Subscription discover(DiscoveryHandler handler, optional ThingFilter filter = null);
};

typedef DOMString DiscoveryMethod;

dictionary ThingFilter {
  DiscoveryMethod method = "directory";
  USVString? url;
  object? fragment;
 };

```

**Comment by zolkis** [comment]
A possible API with direct functions.

```js
callback DiscoveryHandler = undefined(ThingDescription);

partial namespace WOT {
[SecureContext, Exposed=(Window,Worker)]
interface WotDiscovery {
    Promise<undefined> direct(DiscoveryHandler handler, USVString url);
    Promise<Subscription> directory(DiscoveryHandler handler, USVString url);
};

```

With examples like:

```js
let discovery = new WotDiscovery();
await discovery.direct(handler, "https://mythings.my/thing2");
let subs = await discovery.directory(handler, "https://directory.mythings.my/");
...
if (subs.active) {
   await subs.stop();
}
```

That allows for a small variation.

```js
callback DiscoveryHandler = undefined(ThingDescription);

partial namespace WOT {
[SecureContext, Exposed=(Window,Worker)]
interface WotDirectDiscovery {
    Promise<undefined> start(DiscoveryHandler handler, USVString url);
};

[SecureContext, Exposed=(Window,Worker)]
interface WotDirectoryDiscovery extends Subscription {
    Promise<Subscription> start(DiscoveryHandler handler, USVString url);
};
```

The example becomes:

```js
let discovery = new WotDirectDiscovery();
await discovery.start(handler, "https://mythings.my/thing2");

let discovery = new WotDirectoryDiscovery();
await discovery.start(handler, "https://directory.mythings.my/");
...
if (discovery.active) {
    await discovery.stop();
}
```

**Comment by zolkis** [comment]
Yet another variation. I like that `direct()` returns a promise that resolves with a TD.
If somehow we could expose also directory discovery with that pattern, that would also solve the follow-links problem.
That means it could return an [iterable ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), which brings back the `next()` method we wanted to get rid of :).

So it might be that the current discovery API is still the most idiomatic and flexible. 
But now we have a lot of options to discuss :).

**Comment by relu91** [comment]
> Yet another variation. I like that `direct()` returns a promise that resolves with a TD. If somehow we could expose also directory discovery with that pattern, that would also solve the follow-links problem. That means it could return an [iterable ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), which brings back the `next()` method we wanted to get rid of :).
> 
> So it might be that the current discovery API is still the most idiomatic and flexible:
> 
> * it implements an iterable, i.e. a standard and same interface for all discovery methods;
> * therefore it has flow control (script calling `next()`), unlike with callbacks or events (though this is not really a problem because of how JS engines work)
> * it handles errors both before and during discovery (the callback alternative would need to pass 2 callbacks); however, the way it is specified now, is the same as the promise version of directory discovery (only the last error available that was so severe as to stop discovery).
> * extensible with more discovery methods without an API/ABI break (the others can do the same).
> 
> Now we have a lot of options to discuss :).

I agree that the current API can cover the points above. Still, it is an overkill for the simplest use-case:
- Return the list of TDs at this location

I agree there's still a lot to discuss, taking also in mind that the Discovery specification is still ongoing (even though close to the feature freeze).

**Comment by zolkis** [comment]
> Return the list of TDs at this location

Handling a list on the client side is best done with iterators, since this can encapsulate buffering, unlike when we expose arrays of TDs to the scripts. Providing a callback (two, actually) is another pattern, but splitting into `direct()` and `directory()` ends up with different function signatures, whereas with the current design the same function can handle both, based on a string argument "direct" or "directory". 

We could make [Example 9](https://w3c.github.io/wot-scripting-api/#example-fetch-the-thing-description-of-a-thing) and [Example 10](https://w3c.github.io/wot-scripting-api/#example-discover-things-via-directory) with all alternatives as see which works best.

**Comment by JKRhb** [comment]
I guess such an iterator would/should be an [async one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator), right? It seems to me as if an Async Iterable could solve the blocking issue I mentioned above very elegantly.

**Comment by zolkis** [comment]
Yes, we could use an async iterator on the discovery object, they are supported in ECMAScript.

**Comment by JKRhb** [comment]
> Yes, we could use an async iterator on the discovery object, they are supported in ECMAScript.

Okay, great :) Do I see it correctly that we could then handle discovery like so?

```ts
const discovery = new ThingDiscovery({ method: "directory", url: "http://directory.example.org" });

for await (const thingDescription of discovery) { // Note: Has to be within an async function
  console.log("Found Thing Description for " + thingDescription.title);
}
```

If so, I think this would be a very nice solution.

**Comment by danielpeintner** [comment]
Today's Scripting call
* iterator approach seems to be the way to go
* use-case for introduction, exploration phase
* @relu91 wait till discovery spec is settled, see https://github.com/w3c/wot-discovery/pull/274

**Comment by zolkis** [comment]
@JKRhb are you planning to experiment with iterators in the implementation?
If there is any feedback to the API, please make them here.

**Comment by JKRhb** [comment]
I already tried to experiment with Iterators a bit, and it seems to if an `AsyncGenerator` could provide a very elegant solution to the problem (using a class that implements `AsyncIterable` caused some problems for me, as you cannot access class fields from the `AsyncIterator`, as it seems). A first example can be seen below. Maybe this could work for the new API, provided that it can be expressed in WebIDL?

You can experiment with the code yourselves in the Typescript Playground under [this link](https://www.typescriptlang.org/play?target=5#code/JYOwLgpgTgZghgYwgAgCoAtQHMAiEDOCUwADmMAPYjIDeAUMsuWADYQBcy+YxIWdAXzp0ELOPnxpMfHMEIUAbtACetBskTklnAEYUKbONQC8TKAFcIAbmGNxykAmQAqACZyEi6AApzxTty8WACUnACC+A4IAOIQINBwYBRQADwY2HiExGSUIAB8aoyMAO6YbMjeYJj4AHSawErBhUUtniDcyFAEJFT4KKZwxXDAYMgwEGAI6L7EwTYtrb2jJHBQfa6orsgDQyOd3b0QNQBW+FTec+oLyMrAECxb8cXIAApQFAC2chBp0rgERFI5CoeW8XTOLCU2wK4IMSm8KzWEA2rmClxaQiE6hI5h0LGATm4FBIF2ajCqcjqCC0-TGcBYfXmyExwgA9KzkAApcwdOCdIyuT7IACqACUAJLIHqgch8JgUDRoHAiJbIPzAbbIABE6DAYBI+HY7KggxqWBG6FxPOgbUg4Bqng+rOKAGYEM6KGAALSQbjYVkfYYgVkQJTgfCsgBMAAZI5GatGXTUAPIgfHxVmoHCszBgRCYL3dL3AVwwTM4CO5-PAL2IBC14BQGpgVwnM5p1xamx0eyOMbmRzA6jcVZgWTyJRQZSk+iMNijCkyDxeKeap5SDLLyfT9HIefITwDyBQTXRpkwZIaXajbz7xf-LJA3LICgwJh-ceebc1dwTnzqtEyWQYA328Q9wGgbZjFMF0mlnBZ70-FdlBqIkSV3FodC6OAAGsmUYIRFnaAwjhYCgsG8AADAAxCYpmRRV0jlTJARyKhkGKC0mBGcoABIaEQgFsiHZseIgARKIwg8KCPaAAGo5KZFk6BHKAxy3FQLhsIA).

```ts
interface ThingDescription {
  title: string
}

class ThingDiscovery {
  active: boolean = true;

  async *discover(uri: string): AsyncGenerator<ThingDescription> {
    while (this.active) {
        const response = await fetch(uri);
        const parsedTd = await response.json();
        yield new Promise<ThingDescription>(resolve => resolve(parsedTd));
    }
}

  public stop() {
    this.active = false;
  }
}

// Just a random URI pointing to a TD
const uri = "https://raw.githubusercontent.com/w3c/wot-testing/main/events/2022.03.Online/TD/hitachi-esp-idf/TDs/hitachi-acc-air.td.jsonld";

async function startDiscovery() {
  let thingDiscovery = new ThingDiscovery();
  let counter = 0;
  for await (let thingDescription of thingDiscovery.discover(uri)) {
    if (counter === 3) {
      thingDiscovery.stop();
      break;
    }
    console.log(`Fetched a Thing Description with title ${thingDescription.title}`);
    counter++;
  }
}

startDiscovery();
```

**Comment by JKRhb** [comment]
I created a new example which both implements a `next()` method and adds the `start()` method back in. I also cleaned up the example in general, making it clearer that only one TD is actually discovered by the direct method (at least in this case).

<details>
<summary>Third Discovery Example in Typescript</summary>

```ts

interface ThingDescription {
  title: string
}

class WoT {

  discover (uri: string): ThingDiscovery {
    return new ThingDiscovery(uri);
  }

}

class ThingDiscovery implements AsyncIterable<ThingDescription> {

  active: boolean = false;
  private uri: string;

  constructor(uri: string) {
    this.uri = uri;
    this.start();
  }

  public async next()  {
    return await this[Symbol.asyncIterator]().next();
  }

  async* [Symbol.asyncIterator](): AsyncIterator<ThingDescription> {
    if (!this.active) {
      return;
    }

    const response = await fetch(this.uri);
    const parsedTd = await response.json();
    yield new Promise<ThingDescription>(resolve => resolve(parsedTd));
  }

  public stop() {
    this.active = false;
  }

  public start() {
    this.active = true;
  }
}

// Just a random URI pointing to a TD
const uri = "https://raw.githubusercontent.com/w3c/wot-testing/main/events/2022.03.Online/TD/hitachi-esp-idf/TDs/hitachi-acc-air.td.jsonld";

async function startDiscovery() {
  const wot = new WoT();
  const thingDiscovery = wot.discover(uri);
  // thingDiscovery.stop();
  for await (let thingDescription of thingDiscovery) {
    console.log(`Fetched a Thing Description with title ${thingDescription.title}`);
  }
  // Alternative:
  console.log(await thingDiscovery.next());
}

startDiscovery();
```
</details>

**Comment by zolkis** [comment]
Thanks Jan. Minor nit: according to the spec, `start()` is invoked from `discover()`, not from the constructor.

**Comment by zolkis** [comment]
Reviving this issue for a current discussion.

If we use async iterators, then they should be tied to either a ThingDiscovery or to some result objects. 

The current approach with ThingDiscovery objects can handle the "give my any TDs" use case as easily as selecting a specific discovery method, e.g. `direct()`. Also, the ThingDiscovery object has a `start()` and `stop()` method, and implements async iterator for discovery results.

In this model we have to use separate ThingDiscovery objects for different discovery methods.

An alternative would be separate interfaces or functions for each discovery method, but then we lose the generic use case.
Let's take it from here.

**Comment by zolkis** [comment]
After all the discussions, I suggest something like this.

For the various discovery methods, we could have separate interfaces or functions.
```javascript
partial namespace WOT {
    ThingDiscovery discover(optional ThingDiscoveryMethod method);
}

[SecureContext, Exposed=(Window,Worker)]
interface ThingDiscovery {
    readonly attribute boolean active;
    readonly attribute boolean done;
    undefined stop();
    async iterable<ThingDescription>;
};

[SecureContext, Exposed=(Window,Worker)]
interface ThingDirectDiscovery extends ThingDiscovery {
    undefined start(USVString url, optional ThingFilter filter);
}

[SecureContext, Exposed=(Window,Worker)]
interface ThingDirectoryDiscovery extends ThingDiscovery {
    undefined start(USVString url, optional ThingFilter filter);
}
```
and so on, a separate subclass for other discovery methods.
Note that `discover()` returns an object right away, which implements async iterator.
With no args, it implements the generic use case: "discover all reachable TDs using any means provisioned to the user agent".
If args provided, it will return a corresponding instance of ThingDiscovery (we can subclass or describe in algorithms how they will work).


Alternatively, we could integrate @relu91 's proposal (link)

```javascript
partial namespace WOT {
    ThingDiscovery discover();  // or use simple constructor for ThingDiscovery
}

interface ThingDiscovery {
  constructor();
  readonly attribute boolean active;
  readonly attribute boolean done;
  Promise<undefined> start();  // generic use case
  Promise<ThingDescription> startDirectDiscovery(USVString url, optional ThingFilter filter);  // or direct(...)
  Promise<undefined> startDirectoryDiscovery(USVString url, optional ThingFilter filter); // or directory(...)
  undefined stop();
  async iterable<ThingDescription>;
};
```
and so on, for each new discovery method we add a corresponding startXxx() function.
But after one of the start methods is called, the status becomes active, and after that it needs to be stopped before another start can be used, otherwise they return error.

I think the latter is simpler and it covers all use cases. Also, it allows separate algorithms for different discovery methods.
But there we need to discuss the Promise vs iterator details. Also, we need to re-discuss `ThingFilter`.

@relu91 @JKRhb @danielpeintner PTAL

**Comment by zolkis** [comment]
> in the case of direct discovery I would like to get a ThingDescription (and not an iterator were I need to iterate over). I know it MUST be one result or failure

It looks like a misunderstanding. In that case there is a Promise, i.e. you get result or failure.

**Comment by danielpeintner** [comment]
> > in the case of direct discovery I would like to get a ThingDescription (and not an iterator were I need to iterate over). I know it MUST be one result or failure
> 
> It looks like a misunderstanding. In that case there is a Promise, i.e. you get result or failure.

Yes, in your alternative approach... 
The first approach looks like this

```
interface ThingDirectDiscovery extends ThingDiscovery {
    undefined start(USVString url, optional ThingFilter filter);
}
interface ThingDiscovery {
    readonly attribute boolean active;  // this can become 'state', e.g. inactive, direct, directory, ...
    readonly attribute boolean done;  // not sure this is needed any more
    undefined stop();
    async iterable<ThingDescription>;
};
```

For direct discovery this means to me I have to do the following:
1. I need to call `start`
2. I get the async iterator

Am I wrong?

**Comment by zolkis** [comment]
Looks like I also misunderstood your comment @danielpeintner :) 

Yes, the first IDL would use async iterator for direct discovery as well. Not really a practical complication (quite the contrary, actually it is simpler to use in scripts), but one might dispute it in theoretical and aesthetic terms :).

I also prefer the second alternative IDL, mainly because it allows us to specify separate algorithms for various discovery methods. But note this is different from @relu91 proposal from the #222: that thinking was adapted to this approach with iterators, and expressed at differentiating the `start()` methods.

Note that all `startXxx()` methods in the second alternative are temporary names, we can think about better ones.

I'd like to leave @relu91 and @JKRhb the freedom to rethink discovery their own way, and come up with alternative proposals, or modifying the above ones.

**Comment by danielpeintner** [comment]
After the discussion we had in today's call I personally see the following interfaces as a possible way forward...

```javascript
partial namespace WOT {
  ThingDiscovery discover();
};

interface ThingDiscovery {
  // return TD directly
  Promise<ThingDescription> direct(string url);
  // return TDs via Iterator
  DiscoveryIterator directory(string url, ...);
  DiscoveryIterator any(string url, ...);
  // more ?
};

interface DiscoveryIterator {
  // decide which properties we actually need
  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;
  readonly attribute ThingFilter? filter;
  // actual iterator methods
  undefined start();
  undefined stop();
  Promise<ThingDescription> next();
  async iterable<ThingDescription>;
};
```

**Comment by zolkis** [comment]
A few comments,
- I am not sure if `DiscoveryIterator` is the best name, but why not. 
- We should use `USVString` for URLs.
- We need to be able to pass discovery options to methods. Maybe different ones for different methods.
- `start()` is unclear now
- we don't need `next()`
- `any()` is not a good name
- For async methods, we should be able to pass and AbortSignal among the options, if we choose to respect the [design doc](https://w3ctag.github.io/design-principles/#aborting). But I think `stop()` should be fine in this limited context.
- Not sure if we want to keep the factory method, or should we just have a constructor.
The corrected Web IDL for @danielpeintner 's suggestion:

```javascript
partial namespace WOT {
  ThingDiscovery discover();  
};

interface ThingDiscovery {
  constructor();
  Promise<ThingDescription> direct(USVString url, optional ThingFilter options);
  DiscoveryIterator directory(USVString url, optional ThingFilter options);
  DiscoveryIterator queryAll(optional ThingFilter options);
};

interface DiscoveryIterator {
  // decide which properties we actually need
  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;
  readonly attribute ThingFilter? filter;
  undefined stop(); 
  async iterable<ThingDescription>;
};
```

**Comment by zolkis** [comment]
I wonder if we could further simplify. Should we map out direct discovery as a method of its own, and use the term discovery for the rest? Then we don't need a separate iterator interface.
Instead of the former name `fetch()`, we could use less overlapping names like `requestThingDescription()` or `readThingDescription()` .
Also, we could have a constructor for iterator-style discovery, and an async method for direct fetch.
The Web IDL that implements this:

```javascript
partial namespace WOT {
  Promise<ThingDescription> requestThingDescription(USVString url, optional ThingFilter options);
};

interface ThingDiscovery {
  constructor();

  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;  // protocol errors 
  readonly attribute ThingFilter? filter;
 
  // runtime errors (not protocol errors) are handled by Promise
  Promise<undefined> queryDirectory(USVString url, optional ThingFilter options);
  Promise<undefined> queryAll(USVString url, optional ThingFilter options);
  undefined stop();
  async iterable<ThingDescription>;
};
```

**Comment by zolkis** [comment]
Note that the proposal [here (Daniel's modified) ](https://github.com/w3c/wot-scripting-api/issues/364#issuecomment-1305848888) and [here (my last) ](https://github.com/w3c/wot-scripting-api/issues/364#issuecomment-1305850489) are almost the same, except
- the latter has different method names, 
- the latter experiments with returning a promise for starting discovery (algorithm steps will help clarify which approach is better)
- the latter implements async iterable directly.

We can discuss these differences separately, but the starting point is the first proposal (modified from Daniel's). I think it's a good start. It would also allow something like the following:

```javascript
try {
  for await (let td of wot.discover().queryAll()) {
    console.log("Found Thing Description for " + td.title);
  }
} catch(error) {
  console.log("There was an error": + error.message);
}
```

Which is pretty nice, minimal, and feasible (if we define properly how to throw).

@relu91 @JKRhb your turn. :)

**Comment by relu91** [comment]
I read through this issue thread and also read the [Discovery spec](https://w3c.github.io/wot-discovery/#discoverer-process) once again. I think we are getting closer to a consensus. 

Some doubts that I still have:
1. `ThingDiscovery` contains both methods and discovery process status. This may complicate the algorithms because they need to check the weather there is a process already ongoing or not.
2. There might be an use case where the WoT app developer is unsure whether a given URL is for a TDD or a single TD. With this APIs he has to call  `requestThingDescription`, check weather it is a TDD, and then call `queryDirectory`. It would be nice to have a method that cover also this corner case. Maybe we can refactor this `queryDirectory` to `query` and it will act accordingly. 


To solve 1. I would:
```
partial namespace WOT {
  Promise<ThingDescription> requestThingDescription(USVString url, optional ThingFilter options);
};

interface ThingDiscovery {
  constructor();
  // runtime errors (not protocol errors) are handled by Promise
  Promise<ThingDiscoveryProcess> queryDirectory(USVString url, optional ThingFilter options);
  Promise<ThingDiscoveryProcess> queryAll(USVString url, optional ThingFilter options);
  
};

interface ThingDiscoveryProcess {
  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;  // protocol errors 
  readonly attribute ThingFilter? filter;

  undefined stop();
  async iterable<ThingDescription>;

}
 
```

**Comment by zolkis** [comment]
I like the latest approach. We need to think about how future use cases would change the API: local, bluetooth/nfc, multicast etc. I think they could be covered by the `queryAll()` method, or we can define separate methods as well (I prefer the latter, because the dedicated algorithms and separate problem space).

**Comment by danielpeintner** [comment]
Scripting Call 2022-11-14

* Use-cases
  * List of urls (vs. single url)
  * removing duplicates (coming from discovery spec)
  * manual TDD discovery (get TD & detect TDD) vs automatically dealing by providing an url
  * automatic discovery dealing with ThingLinks

TODO / questions:
* update the proposal?
* @ashimura ask developers for priority of the afore mentioned use-cases 
* different ThingFilter options for queryDirectory and queryAll
* What should be under WoT namespace 
* ...

**Comment by zolkis** [comment]
Just writing down what @relu91 proposed (with point 2)
Note that conflicts with the requirement from @danielpeintner that we should not be forced to use iterator when fetching a single TD. 
Now we can't have both, so we need to pick a choice :).
IMHO the more developer friendly option is what's below (no real problem handling an iterator for a single TD).

```js
interface ThingDiscovery {
  constructor();
  // runtime errors (not protocol errors) are handled by Promise
  // query() is manual (script controls the traversal), 
  //    handles both fetching a single TD, and a TDD
  Promise<ThingDiscoveryProcess> query(USVString url, optional QueryFilter options);
 
  // queryAll() leaves all complexity to the implementation, 
  //    and MAY specify URL filters as well
  Promise<ThingDiscoveryProcess> queryAll(optional ExtendedQueryFilter options);
};

interface ThingDiscoveryProcess {
  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;  // protocol errors 
  readonly attribute ThingFilter? filter;

  undefined stop();
  async iterable<ThingDescription>;
};

```

**Comment by danielpeintner** [comment]
I think we are converging :-)

I was asking myself "what" should happen if query(...) gets called with an url of directory. Shall it return the ThingDescription of the Directory or (as in your case) the actual thing TDs behind the directory. I tend to agree with your thinking.

Note: I think `readonly attribute ThingFilter? filter;` in `ThingDiscoveryProcess`  might no longer be necessary since it may be QueryFilter or ExtendedQueryFilter _now_. I would say that this information might not be needed anyway... people could argue we need to store the entry url as well.

> `discoverAll()`. That would address the concern of differing from the style of `produce()` and `consume()`.
> If we have a separate method for reading a TD, that could as well be directly on the WoT object as `requestThingDescription()`.

👍

**Comment by zolkis** [comment]
> Note: I think readonly attribute ThingFilter? filter; in ThingDiscoveryProcess might no longer be necessary 

That is right. Removed.

**Comment by relu91** [comment]
Thank you for writing down the use cases. They fit more or less the ones that I had in mind in the last call. To use a more Discovery spec oriented terminology:
- request generic discovery, given some filters -- the discoverAll() method above. This means letting the runtime support a bunch of known *introduction mechanisms* and automatically *explore* the resulting set of discovered URLs. 

Also, I think use case 2 is supported by 1, right? 

Basically in mind, we should support:
1. Fetch a TD or throw an error (it can be any URL accepted by the protocol binding templates spec)
2. Discovery of URL with filtering ( we could be merciful and if the TD in the URL is not a TDD we can still try to apply the filters but it will result in some implementation costs)
3. Discover what you can. 

Those cover the plausible scenarios in WoT application development:
1. I know exactly which TD I want
2. URL is issued by a third party and I have no means to verify if he is pointing me to a TDD or a TD
3. I want to adapt to the deployment context and try to fetch what the deployer allowed me to do.

**Comment by zolkis** [comment]
> I know exactly which TD I want
> URL is issued by a third party and I have no means to verify if he is pointing me to a TDD or a TD

These 2 could be supported by the `requestThingDescription()` method.

> I want to adapt to the deployment context and try to fetch what the deployer allowed me to do.

That is the `discoverAll()`.

What I am wondering about is the semantics of `discover()` should include only directories (error if not a TDD), or allow fetching a single TD as well (contained in the list, not the TD of the TDD itself, which could be obtained by the `requestThingDescription()`.

**Comment by zolkis** [comment]
The Web IDL discussed in the call.

```js
partial namespace WOT {
  // get a single TD, or fail
  Promise<ThingDescription> requestThingDescription(USVString url);

  // Manual traversal of TDD, but also handles single TD at URL
  Promise<ThingDiscoveryProcess> exploreDirectory(USVString url, optional ThingFilter options);
 
  // discoverAll() leaves all control and complexity to the implementation, 
  //    and MAY specify URL filters as well
  Promise<ThingDiscoveryProcess> discover(optional ExtendedThingFilter options);
};

interface ThingDiscoveryProcess {
  readonly attribute boolean active;
  readonly attribute boolean done;
  readonly attribute Error? error;  // protocol errors 

  undefined stop();
  async iterable<ThingDescription>;
};

dictionary ThingFilter {
  // USVString? query;
  object? fragment;
};

dictionary ExtendedThingFilter {
  USVString? url;
};

```

**Comment by danielpeintner** [comment]
Scripting Call 2022-11-21
* @relu91 @JKRhb  will work on a first PR of the above API
* others will review

**Comment by zolkis** [comment]
In the call on 28.11.2022 we discussed how to expose local Things: via a filter, or via a separate method.
It seems local discovery involves an introduction phase and exploration phase, therefore a separate method and algorithm would be better suited (later).

**Comment by JKRhb** [comment]
Hi everyone :) I was dealing with implementing directory discovery in dart_wot lately and I was wondering a bit about how exactly the process should work here:

1. Is the directory URL supposed to be the directory's Thing Description? Or is it supposed to point to a resource related to the `things` property of the directory?
2. In the case that the URL is supposed to point to the TDD's Thing Description, should the implementation first consume the TD and then read the `things` property? Or is this implementation-specific?

Sorry if the answer to these questions should be obvious, unfortunately, I haven't really been able to follow the discussions in the TF for the last couple of months :/ In any case: Thank you! :)

**Comment by JKRhb** [comment]
I think we could consider closing this issue (since we now have a new API in place) and maybe create a new issue from my comment above (https://github.com/w3c/wot-scripting-api/issues/364#issuecomment-1554391976) that deals with describing the algorithm used for the `exploreDirectory` method more explicitly.

**Comment by relu91** [comment]
Call 11 Dec
- @JKRhb we should close this and create a new issue.
