### ISSUE TITLE
Recent ReSpec Warnings - Found definition for "XYZ", but nothing links to it.

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#365]
Recently we got many of ReSpec Warnings, see https://w3c.github.io/wot-scripting-api/
e.g. Found definition for "user agent", but nothing links to it. This is usually a spec bug! 

![grafik](https://user-images.githubusercontent.com/11281461/149725828-e032c2d2-1688-48fc-a2fd-59bfcf84d842.png)

**Comment by danielpeintner** [comment]
relates to https://github.com/w3c/wot-scripting-api/issues/357

**Comment by danielpeintner** [comment]
https://github.com/w3c/wot-scripting-api/pull/367 resolves most of the warnings, 4 are remaining

![grafik](https://user-images.githubusercontent.com/11281461/150339110-c86a13c6-d6b7-4376-b34e-b2615a3e4eb8.png)

The first 2 warnings are 
* "user agent" is defined in https://w3c.github.io/wot-scripting-api/#conformance but not used 
* "JSON-LD" is defined in https://w3c.github.io/wot-scripting-api/#terminology-and-conventions  but not used 

Shall we remove the definitions or add a "lint-ignore" CSS class.

The other 2 warnings are about W3C Recommendation track documents.
Hence I added  `noRecTrack` to `true` in https://github.com/w3c/wot-scripting-api/pull/368
Note: we do have Security and Privacy section but not 2 separate ones.

**Comment by zolkis** [comment]
We can remove the definition for user agent and just the term from [Infra](https://infra.spec.whatwg.org/#user-agent), `[= user agent =]`
https://respec.org/xref/?term=user+agent

**Comment by zolkis** [comment]
We can use only a link to JSON LD, and remove the definition?

We should split the Security and Privacy into two separate sections, let's create an issue and a PR for that.

**Comment by danielpeintner** [comment]
> We should split the Security and Privacy into two separate sections, let's create an issue and a PR for that.

Not necessary at the moment.. since we are not on REC track. Can still do that in the future...
