### ISSUE TITLE
Check alignments with Architecture 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#376]
In the editors call the following request were made by @mlagally 

1. Check [terminology of Architecture document](https://w3c.github.io/wot-architecture/#terminology) w.r.t. Scripting
   * "Consuming a Thing"
   * "Exposing a Thing"
   * ..
2. Check the scripting sections in Arch document
   * [8.6 WoT Scripting API](https://w3c.github.io/wot-architecture/#sec-scripting-api)
   * [9.3 WoT Scripting API](https://w3c.github.io/wot-architecture/#wot-scripting-api)

**Comment by danielpeintner** [comment]
I read the *relevant* parts of the Architecture document and found just one aspect I would like to change.

### [8.6 WoT Scripting API](https://w3c.github.io/wot-architecture/#sec-scripting-api)

I would say we should change
> the programming interface that allows scripts to discover, fetch, consume, produce, and expose WoT Thing Descriptions.

to

> the programming interface that allows scripts to discover, consume, produce, and expose WoT Thing Descriptions.

I don't think we specify fetching TDs.

Moreover, "produce" and "expose" are somewhat synonyms to me. Shall we merge it into one to be aligned with our 3 conformance classes?
Any thoughts?

**Comment by zolkis** [comment]
Yes to

> the programming interface that allows scripts to discover, consume and produce WoT Thing Descriptions.

**Comment by danielpeintner** [comment]
Today's Scripting Call 
* @danielpeintner will work on PR for architecture 
* @relu91 plans to double check the according sections

**Comment by danielpeintner** [comment]
Scripting Call 2022-04-04

Decided to close.
