### ISSUE TITLE
ThingModel TypeScript defintition misses package-lock.json

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#379]
see https://github.com/w3c/wot-scripting-api/tree/main/typescript/thing-model

Question: 
* Shall we add one 
 OR 
* do we actually need it in general?

**Comment by relu91** [comment]
thing-model is a subpackage of the Typescript project. Therefore the lock file is shared in the root folder: 
https://github.com/w3c/wot-scripting-api/blob/main/typescript/package-lock.json

**Comment by danielpeintner** [comment]
I see. On the other hand why do the other 2 TS subfolders have it ?

**Comment by relu91** [comment]
> I see. On the other hand why do the other 2 TS subfolders have it ?

Good point maybe is just a leftover 🤔 . Let me check!

**Comment by danielpeintner** [comment]
today's scripting call
*  package-lock.json in sub-directories are to be removed
* @danielpeintner will provide PR
