### ISSUE TITLE
Use-case due diligence

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-scripting-api#392]
Please provide an assessment of the use cases that are covered by the current spec.
Can you  please do a MR with an update of the scripting column to https://github.com/w3c/wot-usecases/blob/main/USE-CASES/coverage.csv
To separate multiple requriements in the same column, you can use "/"

**Comment by danielpeintner** [comment]
We discussed this issue in today's scripting  call.

The consensus is that scripting could be marked in *all* use-cases. Scripting is a "tool" and not limited to a given use-case... it is applicable to all domains / use-cases.

@mlagally can explain the expectations ?

**Comment by mlagally** [comment]
@danielpeintner , @mmccool Please see comments in https://github.com/w3c/wot-usecases/issues/189

**Comment by danielpeintner** [comment]
Note: STALLED for the time being.

**Comment by relu91** [comment]
Call 29/01:
- Deprecated by the new work done by the Use cases task force. We'll add new follow-up issues when we coordinate with the Use cases task force.
