### ISSUE TITLE
DataSchemaValue misaligned in TS definitions

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#403]
> Technically [InteractionInput](https://w3c.github.io/wot-scripting-api/#the-interactioninput-type) is either a ReadableStream or any... which can be undefined.

Good catch I was using TS and in our type definitions DataSchemaValue (which in WebIDL is any) is more restrictive. See https://github.com/w3c/wot-scripting-api/blob/main/typescript/scripting-api/index.d.ts#L87 . I'll make a PR but now I wondering what we should do about that DataSchemaValue definition... I think we can discuss this in another Issue.

_Originally posted by @relu91 in https://github.com/w3c/wot-scripting-api/issues/402#issuecomment-1134359087_

**Comment by danielpeintner** [comment]
Call 2022-05-30
check whether it is possible to replace `any` in WebIDL with proper types for `DataSchemaValue`?
@zolkis recursive definition not possible (e.g., `DataSchemaValue[]`)) 
@relu91 aligned already based on prose?

**Comment by relu91** [comment]
> @relu91 aligned already based on prose?

I think the prose is already good: 
> DataSchemaValue is an [ECMAScript value](https://www.ecma-international.org/ecma-262/11.0/index.html#sec-ecmascript-data-types-and-values) that is accepted for [DataSchema](https://w3c.github.io/wot-scripting-api/#dfn-dataschema) defined in [[WoT-TD](https://w3c.github.io/wot-scripting-api/#bib-wot-td)] (i.e. null, boolean, number, string, array, or object).

Perhaps, we can move the list of the admitted values from the parenthesis outside, to feel more official and less like an optional explanatory text.

**Comment by danielpeintner** [comment]
Call 2022-07-04
* @relu91 w.r.t. quoted text, move parenthesized text out
* @relu91 otherwise we can close issue (check again whether WebIDL allows for recursive definitions).

**Comment by danielpeintner** [comment]
@danielpeintner to propose PR, as mentioned [here](https://github.com/w3c/wot-scripting-api/issues/403#issuecomment-1173699833) we should move parenthesized text out. 

Afterwards close this issue.
