### ISSUE TITLE
Incosistency in emit property changed

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#407]
From https://github.com/eclipse/thingweb.node-wot/pull/775#pullrequestreview-1002587641

> Reading the [spec algorithm](https://www.w3.org/TR/wot-scripting-api/#the-emitpropertychange-method) we are mentioning to use also the observeHandler to get the new value of the property and using the readHandler only as a fallback. However, this is a little bit counterintuitive if compared to what we are doing for Events. I believe that a regular user would expect that the observeHanlder is used when someone "observes" a property not when we want to send the new value. We might need some renaming/refactoring

**Comment by danielpeintner** [comment]
Call 2022-07-04
*  different understanding how property change event is to be handled.
* get feedback from PlugFest
* @relu91 remove Step 6 in (https://www.w3.org/TR/wot-scripting-api/#the-emitpropertychange-method) for now ([[observeHandler]] ). Consider adding a dedicated handler.

**Comment by danielpeintner** [comment]
Call 2022-07-11
* @relu91 could also use a dedicated handler like `emitPropertChange` handler instead of using [[readHandler]]
* do we have such use-cases? If not we should stick with [[readHandler]] only 
* @danielpeintner will propose PR.
