### ISSUE TITLE
W3C calendar invites use wrong IRC channel

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#418]
#wot-scripting instead of #wot-script

see for example https://www.w3.org/groups/ig/wot/calendar#card-89618153-e1aa-4e61-9805-01f7227f3b97-20220725T070000

**Comment by danielpeintner** [comment]
@mmccool may I ask you to fix the IRC channel in all invites. Thanks!

**Comment by mmccool** [comment]
Done.  Changed to wot-script.
