### ISSUE TITLE
Next Charter - Ideas / Proposals

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#422]
## New W3C Process

In https://github.com/w3c/wot-scripting-api/issues/354 we discussed a possible change w.r.t. the W3C Process.

3 possible choices
* Informative Note (Status quo)
* Formal Note, see [Note Track](https://www.w3.org/2021/Process-20211102/#note-track). (allows as to use conformance sections and normative statements)
* REC track

Note: We can make up our mind as a task-force but need to check with the entire group in the end.

## Next Charter Topics

see https://github.com/w3c/wot-scripting-api/issues/352

## Breaking Changes in API

* Discovery (see for example WIP PRs)
* Exposing process (https://github.com/w3c/wot-scripting-api/issues/409)

**Comment by zolkis** [comment]
I wonder about the following.

1. For the Scripting API, would it make sense to include it into the CG, rather than the WG, and instead of a WG Note, should it be one or more CG spec? A counter-argument would be that the CG focuses more on a web-specific protocol for WoT, rather than a Scripting API.

3. We could include a provisioning API (a.k.a. management API) in a new, separate document, that would have different security context.

4. In the extreme, the current conformance classes could be made into separate specifications, making things more clear.

**Comment by danielpeintner** [comment]
Note: CGs don't get W3C team support and the current CG charter does *not* mention any deliverables.

**Comment by danielpeintner** [comment]
Note: https://github.com/w3c/wot/pull/1029 is the place  where possible deliverables for the next charter should go...

**Comment by mmccool** [comment]
Could you make an actual proposal as an md file in [deliverable-proposals](https://github.com/w3c/wot/tree/main/proposals/deliverable-proposals)?   This would be helpful even if we keep the status quo of the scripting API being informative, but I think we should at least discuss whether it should be a normative (but probably optional) spec.

**Comment by danielpeintner** [comment]
In yesterdays Pre-TPAC meeting we concluded to use a "Normative Note" for Scripting.

Having said that, @mmccool shall we still create an MD file for [deliverable-proposals](https://github.com/w3c/wot/tree/main/proposals/deliverable-proposals). The *old* charter simply lists scripting under [other deliverables](https://www.w3.org/2022/07/wot-wg-2022.html#other-deliverables).

**Comment by danielpeintner** [comment]
I created https://github.com/w3c/wot/pull/1043 as starting point. Please comment.

BTW, I don't think we need to add a lot of prose since we will most likely be listed again under [other deliverables](https://www.w3.org/2022/07/wot-wg-2022.html#other-deliverables).

**Comment by danielpeintner** [comment]
FYI: https://github.com/w3c/wot/pull/1043 has been merged today by @mmccool.

Updates should go to https://github.com/w3c/wot/blob/main/charters/wot-wg-2023-draft.html

**Comment by danielpeintner** [comment]
Ads discussed today I created a PR against the current WG charter, see https://github.com/w3c/wot/pull/1068

Please have a look and comment.

**Comment by relu91** [comment]
Call 20/02:
- Re-evaluate with the whole group whether it makes sense to change the spec type from Note to Recommendation

**Comment by danielpeintner** [comment]
I agree, I think we can close this issue. Charter has been settled by now.

Next Charter Topics can be found in https://github.com/w3c/wot-scripting-api/issues/352 and other [API-improvement](https://github.com/w3c/wot-scripting-api/labels/API-improvement) topics under the according label.
