### ISSUE TITLE
Consider aligning with IntersectionObserver

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#427]
In the past, there have been attempts to use Observers in the WoT Scripting spec.
There is the [Intersection Observers](https://w3c.github.io/IntersectionObserver/) spec, with example application in the [Compute Pressure](https://wicg.github.io/compute-pressure/#dom-pressureobserver) spec.

We can continue the current design using callbacks and subscriptions, just take a look if we could leverage some synergy with this API, for instance [IntersectionObserver::takeRecords()](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-takerecords).

**Comment by relu91** [comment]
There are some interesting ideas on both specs. But I don't think we can re-use them as they are, they were designed for specific use cases that don't overlap nicely with our `subscribe` and `observe` operations. 

We can still align with their API design as you suggested, in practice, this means refactoring the [Subscription interface](https://w3c.github.io/wot-scripting-api/#the-subscription-interface) to have the `observe`, `unobserve` and `disconnect` methods. What I think fits less in our use cases is how the Observer is created and used. 

Both API examples above, create generic observers that can be used to observe similar events for a lot of different objects.  This use case is far more marginal in a regular wot application where you probably have just a bunch of `ConsumedThing` with different events each that need tailored logic.

**Comment by relu91** [comment]
Call 24/04/2023:
- @relu91 check the comment above there is no clear overlap with our use cases
- @zolkis keep it open so that we can reconsider it for further designs.

**Comment by relu91** [comment]
I'm not sure about the value of keeping this open. Shall we re-discuss it?

**Comment by relu91** [comment]
Call 12/11
- @zolkis we can close it
