### ISSUE TITLE
Definition missing for "discovery results"

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#437]
due to https://github.com/w3c/wot-scripting-api/pull/405

![grafik](https://user-images.githubusercontent.com/11281461/196145715-50dcc993-d102-4448-a19f-0491d27fb623.png)

**Comment by zolkis** [comment]
The `Symbol.asyncIterator` of the ThingDiscovery object replaces the "discovery results" internal slot. We need to rephrase with correct asyncIterator vocabulary and references to algorithms. For instance, the `start()` and  `next()` methods might need revisiting.

**Comment by zolkis** [comment]
With #441 merged, I think we can close this.
