### ISSUE TITLE
Support for Capabilities

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#44]
Capabilities represent a functionality for a Thing that is accessed by an interaction pattern consisting of zero or more properties, actions and events, but at least one of these.
(placeholder for link to M. Koster's presentation)
Capability names are standardized AFAIU.

Scripting should support Capabilities at the following levels:
- discovery filters (discover Things with given capabilities)
- ExposedThing (create Thing/TD with scripting)
- ConsumedThing (changed structure).

This would be a future feature unless the group can converge fast on the concept.

**Comment by mmccool** [comment]
to summarize the discussion on email:
- I mentioned that the "sub-Thing" pattern (i.e. link to a separate Thing Description for part of a single device's interface) may also be used in some cases for sub-interfaces, eg Management Thing, especially when you want different levels of access (a secure link can be used that requires different access rights via TLS etc).
- Noting Capabilities via "labels" can be orthogonal to this.   For instance, a link to a sub-Thing might in fact be labelled with a Capability (eg. a link to a Management sub-think might be labelled with a "Management" Capability).

**Comment by zolkis** [comment]
Obsolete.
