### ISSUE TITLE
Editorial: use map/get when referring to object's properties

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#444]
Throughout the spec, change ```|object|'s "key"``` to ```|object.{{TypeDefinition/key}}|```, see
https://infra.spec.whatwg.org/#example-map-get

**Comment by relu91** [comment]
I propose closing this as I verified that is some places we used `|object.{{TypeDefinition/key}}|` notation. I'd open concrete issues when somebody verifies a specific misalignment in the text.

**Comment by relu91** [comment]
Call 11/12
- @zolkis I cannot find any problems, we can close it.
