### ISSUE TITLE
null initialization necessary for optional method arguments?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#445]
> > If we don't need null initialization, or init with default values, we just leave it without init.
> 
> I don't think we need initialization for `emitEvent(...)`. On the contrary, it seem to cause issues as @relu91 alluded.
> 

Yes exactly, I'd remove the `null` initialization here. About the other places, let's talk about it in an issue (?) or maybe directly on a dedicated PR.

_Originally posted by @relu91 in https://github.com/w3c/wot-scripting-api/issues/442#issuecomment-1350877086_

**Comment by danielpeintner** [comment]
As mention in https://github.com/w3c/wot-scripting-api/pull/442#issuecomment-1350504813 we have many methods that uses null initialization
* Promise<InteractionOutput> readProperty(DOMString propertyName,
                              optional InteractionOptions options = null);

* Promise<InteractionOutput> invokeAction(DOMString actionName,
                              optional InteractionInput params = null,
                              optional InteractionOptions options = null);

* ThingDiscovery discover(optional ThingFilter filter = null);
* ...

I don't think they are needed.

The TypeScript destinations don't have that either, see for example
https://github.com/w3c/wot-scripting-api/blob/6fcfdb65fbec2af5cc5b6243ee09d7ae69388a25/typescript/scripting-api/index.d.ts#L114

I can provide a PR if you are okay with removing them...

**Comment by danielpeintner** [comment]
Note: I created https://github.com/w3c/wot-scripting-api/pull/461 but this PR does not remove null initialization since WebIDL seems to require it (see _more_ information in PR itself).

**Comment by zolkis** [comment]
For the record: Web IDL requires that optional dictionaries are initialized by the `default dictionary` that is the `{}` constant. See the relevant Note in https://webidl.spec.whatwg.org/#idl-constants
