### ISSUE TITLE
Check Internal slots for events

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#447]
_Originally posted by @relu91 in https://github.com/w3c/wot-scripting-api/issues/424#issuecomment-1356332947_

**Comment by zolkis** [comment]
I am not sure we need internal slots for events (specified in the spec).
The question with internal slots is always whether is it helpful to explicitly refer to them, can't they be encapsulated by the implementations? We need internal slots if algorithms need to refer to internal data private to implementations.

But we do need internal slots to manage event subscriptions. Is that what was meant under this issue?

**Comment by relu91** [comment]
I was referring to `eventHandler`, `subscribeHandler`, `unsubscribeHandler` internal slots mentioned in the corresponding algorithms (e.g. https://www.w3.org/TR/wot-scripting-api/#handling-events).
