### ISSUE TITLE
Clean-up Scripting API wiki page

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#529]
On our [wiki page](https://www.w3.org/WoT/IG/wiki/WG_WoT_Scripting_API_WebConf) we have a long list of agendas dating back to 23 November 2020.

Moreover, we have some meetings minutes linked for 2020, 2017 and 2016 (not sure why 2018 and 2019 is missing?)

I think we can (and should) clean-up the page a bit. Maybe something like marketing does with [Old_Agendas](https://www.w3.org/WoT/IG/wiki/Marketing_WebConf#Old_Agendas).

Maybe we can start with the year 2021 and remove *older* entries...

What do people think?

**Comment by danielpeintner** [comment]
Note:
* I created a section about [old agendas](https://www.w3.org/WoT/IG/wiki/WG_WoT_Scripting_API_WebConf#Old_Agendas) linking to them
* There is one subsection [Stash](https://www.w3.org/WoT/IG/wiki/WG_WoT_Scripting_API_WebConf#Stash) which I would propose to remove as well

With above points done I would consider this issue to be done also.

**Comment by relu91** [comment]
Thanks!

> There is one subsection [Stash](https://www.w3.org/WoT/IG/wiki/WG_WoT_Scripting_API_WebConf#Stash) which I would propose to remove as well

I'm ok for removing it.

**Comment by relu91** [comment]
Call 22/01:
- Stash section removed.
