### ISSUE TITLE
A mistake in subscribeEvent logic

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-scripting-api#540]
When subscribing for an Event ([see, number 6](https://www.w3.org/TR/wot-scripting-api/#the-subscribeevent-method)), it is stated that if an active subscription does NOT exist, a NotAllowedError must be thrown. However, I believe it is the other way around as it is described in observing a property

**Comment by relu91** [comment]
I noticed also that the text in observe property contains a problem with the reference to the method map/exists:
![image](https://github.com/w3c/wot-scripting-api/assets/3170227/72808ead-bcd0-4465-881b-2cd7443ab5b3)
