### ISSUE TITLE
WebIDL vs. prose mismatch w.r.t. ThingPropertyInit

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#66]
The spec defines in WebIDL (see https://w3c.github.io/wot-scripting-api/#dom-thingpropertyinit) that configurable is by default  true.

The text that follows states the opposite.

> The configurable attribute defines whether the Property can be deleted from the object and whether its properties can be changed. The default value is false.

**Comment by zolkis** [comment]
To be corrected to `false` in WebIDL. The text is to be corrected as follows:

> The configurable attribute defines whether the Property can be deleted from the object and whether its type can be changed. The default value is false.
