### ISSUE TITLE
ConsumedThing interface: The url read-only attribute represents the URL of the Thing

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#74]
What is the URL of the Thing?
Things can have different links in their Interactions, so that no common base URL can be assigned.

I guess, it should say the URL of the TD of the Thing? This will not make sense for a split into fetch() and consume() or for consume() based on a description string.

**Comment by zolkis** [comment]
Yes, we discussed this needs to be clarified. Thanks for creating an issue for tracking it.

**Comment by zolkis** [comment]
Should we have a `baseURL` on a Thing?

**Comment by mkovatsc** [comment]
No. The `base` field is just an optimization over having long, absolute URIs in each `href` field.

I think there is confusion around what the base URI would mean, which URIs can be stable, and what is actully needed for identification of a Thing instance in regard to IoT, mobility, changing network addresses, etc. See also https://github.com/w3c/wot-thing-description/issues/105

**Comment by zolkis** [comment]
Obsoleted by #113.
