### ISSUE TITLE
JavaScript property management in the WoT Scripting API

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#77]
#70 opened a discussion on JavaScript property management with `writable`, `enumerable`, and `configurable` (not to be confused with the TD writable for TD Properties!).

I would not expose this complexity to WoT Scripting API users. It just creates confusion. Since the Scripting API objects are not generic JavaScript objects, but standardized types, I do not even see the need for it.

**Comment by zolkis** [comment]
OK, we can separate TD property management from implementation object property management, but we still do need to specify what language specific descriptors an implementation should use and what is the mapping with TD properties. This is mostly text, so the enums will be removed from WebIDL.

**Comment by zolkis** [comment]
For better alignment with the TD spec, we could remove the `enumerable` and `configurable` attributes from ThingPropertyInit, and add `observable`.  

Indeed, Thing Properties are not properties on a JS object (though there is an issue proposing exactly that) but internal slots on the Thing object that carry all information from the TD related to the Property.

**Comment by zolkis** [comment]
Addressed by #86.
