### ISSUE TITLE
Interaction Inits: @type = pattern ∪ semanticTypes

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#81]
While implementing a proxy, it turned out that the name `semanticTypes`, which is not equal to TD's `@type`, is actually quite good, because `semanticTypes` only contains the additional semantic annotations, but not the Interaction Pattern such as `Property`. The latter is anyway given already, since we do `addProperty`etc.

Lets keep it that way and document clearly that `semanticTypes` is a subset of `@type`.

**Comment by zolkis** [comment]
Obsoleted by #113.
