### ISSUE TITLE
Align with top-level 'link' field of the TD (for Prague WD) 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#93]
TD plans to add a new field "link" for Prague (see https://github.com/w3c/wot-thing-description/issues/94)

We might consider adding this to scripting also.

**Comment by mkovatsc** [comment]
So far `link` is only planned for informative metadata than does not need processing by the runtime. For now, they all shall be simply passed on to the application.

**Comment by zolkis** [comment]
The API could look like this:

```javascript
dictionary TDLink {
  USVString href;
  DOMString rel;
  USVString mediaType;
};

partial interface ConsumedThing {
  sequence<TDLink> getLinks();  // throws on error
};
```

**Comment by zolkis** [comment]
I have prepared a PR to add this. Let me know if I should file it.

**Comment by mkovatsc** [comment]
`rel` and `mediaType` should be optional, as I guess we also need this definition for `ExposedThing`.

[RFC 8288](https://tools.ietf.org/html/rfc8288#section-2.2) now leaves it open which target attributes exist; they may depend on the `rel` type or the link serialization (such as our TD). In the next step, we will probably need to allow for arbitrary attributes, as domain-specific contexts may define such attributes for the TD link serialization.

**Comment by zolkis** [comment]
By default all dictionary members are optional, so we need to make `href` a `required` property.

**Comment by zolkis** [comment]
Handled by #113.
